# AD.CLS
QFALC=IV,NBO
QFPLC=IV,NBO

# AD.LIM - Aerodrome
QFAAH=IV,BO
QFAAM=IV,NBO
QFAAP=IV,NBO
QFAAR=IV,NBO
QFALB=IV,NBO
QFALH=IV,NBO
QFALI=I,NBO
QFALV=V,NBO
QFALT=IV,NBO

# AD.LIM - Heliport
QFPAH=IV,BO
QFPAM=IV,BO
QFPAP=IV,BO
QFPAR=IV,BO
QFPLB=IV,BO
QFPLT=IV,BO
QFPLI=I,BO
QFPLV=V,BO