# AD.CLS
QFALC=IV,NBO
QFPLC=IV,NBO

# AD.LIM - Aerodrome
QFAAH=IV,BO
QFAAM=IV,NBO
QFAAP=IV,NBO
QFAAR=IV,NBO
QFALB=IV,NBO
QFALH=IV,NBO
QFALI=I,NBO
QFALV=V,NBO
QFALT=IV,NBO

# AD.LIM - Heliport
QFPAH=IV,BO
QFPAM=IV,BO
QFPAP=IV,BO
QFPAR=IV,BO
QFPLB=IV,BO
QFPLT=IV,BO
QFPLI=I,BO
QFPLV=V,BO

# RWY.CLS
QMRLC=IV,NBO
QFHLC=IV,NBO

# RWY.LIM - Runway
QMRAH=IV,BO
QMRAM=IV,NBO
QMRAP=IV,NBO
QMRAR=IV,NBO
QMRLB=IV,NBO
QMRLH=IV,NBO
QMRLI=I,NBO
QMRLL=IV,NBO
QMRLV=V,NBO
QMRLT=IV,NBO
