package com.example.digitalnotam.scenario.rwycls;

import com.example.digitalnotam.baseline.*;
import com.example.digitalnotam.domain.Notam;
import com.example.digitalnotam.workflow.ScenarioBuilder;
import com.example.digitalnotam.xml.CommonDigitalNotamBuilder;
import org.w3c.dom.*;
import java.nio.file.Path;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public final class RwyClsScenarioBuilder implements ScenarioBuilder {
    private static final Path BLUEPRINT=Path.of("data","virtual data","Donlon_2025","Donlon","Digital NOTAM","DN_RWY.CLS_1_full_runway_closure.xml");
    private final CommonDigitalNotamBuilder common=new CommonDigitalNotamBuilder();private final BaselineRunwayCatalog runways=new BaselineRunwayCatalog();private final BaselineAirportHeliportCatalog airports=new BaselineAirportHeliportCatalog();private final RwyClsScenarioValidator validator=new RwyClsScenarioValidator();
    public String scenario(){return "RWY.CLS";}
    public Document build(Notam n)throws Exception{
        if(!"EADD".equals(n.airport()))throw new IllegalArgumentException("RWY.CLS 第一版仅支持 EADD");if(!"CLSD".equals(n.eventDescription()))throw new IllegalArgumentException("RWY.CLS 状态必须为 CLOSED");
        Instant start=Instant.parse(n.effectiveStart()),end=Instant.parse(n.effectiveEnd());var airport=airports.find(n.airport(),start,end);var target=runways.resolve(n.airport(),n.runwayUuid(),n.rwyTargetType(),n.runwayDirectionUuid(),start,end);
        Document d=common.populate(BLUEPRINT,n);Element root=d.getDocumentElement(),event=CommonDigitalNotamBuilder.one(d,CommonDigitalNotamBuilder.EVENT,"Event");Element eventMember=(Element)event.getParentNode();Element directionTemplate=null,closedTemplate=null;List<Node> remove=new ArrayList<>();
        for(Node node=root.getFirstChild();node!=null;node=node.getNextSibling())if(node instanceof Element member&&"hasMember".equals(member.getLocalName())){Element feature=firstElement(member);if(feature!=null&&"RunwayDirection".equals(feature.getLocalName())){if(directionTemplate==null){directionTemplate=(Element)member.cloneNode(true);closedTemplate=(Element)closedWrapper(feature).cloneNode(true);}remove.add(member);}}
        if(directionTemplate==null||closedTemplate==null)throw new IllegalArgumentException("RWY.CLS 蓝图缺少 RunwayDirection/CLOSED availability");for(Node node:remove)root.removeChild(node);removeFeatureLabelComments(root);
        regenerateIds(d);String eventUuid=UUID.randomUUID().toString();event.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","uuid."+eventUuid);CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.GML,"identifier").setTextContent(eventUuid);CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"name").setTextContent(airport.designator()+" "+airport.name());
        Element fir=CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"concernedAirspace");link(fir,airport.firUuid(),airport.firDesignator()+" FIR");Element ahp=CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"concernedAirportHeliport");link(ahp,airport.uuid(),airport.designator()+" "+airport.name());CommonDigitalNotamBuilder.setNotam(d,"affectedFIR",airport.firDesignator());CommonDigitalNotamBuilder.setNotam(d,"location",airport.locationIndicatorIcao().isBlank()?airport.designator().substring(0,2)+"XX":airport.locationIndicatorIcao());
        for(var direction:target.directions()){Element member=(Element)directionTemplate.cloneNode(true),feature=firstElement(member);regenerateIds(feature);feature.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","uuid."+direction.uuid());CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.GML,"identifier").setTextContent(direction.uuid());Element slice=CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.AIXM,"RunwayDirectionTimeSlice");BaselineAirportHeliportCatalog.first(slice,"sequenceNumber").setTextContent(Integer.toString(direction.sequenceNumber()+1));for(Element wrapper:new ArrayList<>(BaselineAirportHeliportCatalog.directChildren(slice,"availability")))slice.removeChild(wrapper);removeAvailabilityComments(slice);Element extension=directChild(slice,"extension");Node firstNormal=null;for(Element normal:direction.normalAvailabilities()){Node imported=d.importNode(normal,true);slice.insertBefore(imported,extension);if(firstNormal==null)firstNormal=imported;}Element closed=(Element)d.importNode(closedTemplate,true);regenerateIds(closed);Element availability=BaselineAirportHeliportCatalog.first(closed,"ManoeuvringAreaAvailability");clearOptional(availability);if(!"CONTINUOUS".equals(n.scheduleMode()))addSchedule(d,availability,n);addAnnotation(d,availability,n.reason(),true);addAnnotation(d,availability,n.remarks(),false);slice.insertBefore(closed,extension);if(firstNormal!=null)slice.insertBefore(d.createComment(" The baseline status of the runway direction "),firstNormal);slice.insertBefore(d.createComment(" The availability status of the runway direction during the event "),closed);Element theEvent=CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.EVENT,"theEvent");link(theEvent,eventUuid,airport.designator()+" "+target.runway().designator()+" DNOTAM RWY.CLS");root.appendChild(d.createComment(" "+target.runway().type()+" "+direction.designator()+" "));root.appendChild(member);}
        validator.validate(d,n,target);return d;
    }
    public void validate(Document d,Notam n){try{validator.validate(d,n,runways.resolve(n.airport(),n.runwayUuid(),n.rwyTargetType(),n.runwayDirectionUuid(),Instant.parse(n.effectiveStart()),Instant.parse(n.effectiveEnd())));}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException(e.getMessage(),e);}}
    private static void addSchedule(Document d,Element a,Notam n){if(!n.scheduleStart().matches("(?:[01]\\d|2[0-3]):[0-5]\\d")||!n.scheduleEnd().matches("(?:[01]\\d|2[0-3]):[0-5]\\d"))throw new IllegalArgumentException("RWY.CLS schedule 必须使用明确的 HH:mm 时间");List<String> days=switch(n.scheduleMode()){case"DAILY","DATES"->List.of("ANY");case"WEEKDAYS"->Arrays.stream(n.scheduleDay().split(",")).map(String::trim).filter(x->!x.isBlank()).toList();default->throw new IllegalArgumentException("不支持的 RWY.CLS schedule: "+n.scheduleMode());};if("WEEKDAYS".equals(n.scheduleMode())&&(days.isEmpty()||days.size()!=new HashSet<>(days).size()||!Set.of("MON","TUE","WED","THU","FRI","SAT","SUN").containsAll(days)))throw new IllegalArgumentException("Weekdays 必须使用不重复的 MON-SUN");if("DATES".equals(n.scheduleMode())&&(n.scheduleStartDate().isBlank()||n.scheduleEndDate().isBlank()||LocalDate.parse(n.scheduleStartDate()).isAfter(LocalDate.parse(n.scheduleEndDate()))))throw new IllegalArgumentException("Dates schedule 日期范围无效");Element before=BaselineAirportHeliportCatalog.first(a,"operationalStatus");for(String day:days){Element interval=e(d,"timeInterval"),sheet=id(d,"Timesheet");interval.appendChild(sheet);add(d,sheet,"timeReference","UTC");if("DATES".equals(n.scheduleMode())){add(d,sheet,"startDate",date(n.scheduleStartDate()));add(d,sheet,"endDate",date(n.scheduleEndDate()));}add(d,sheet,"day",day);add(d,sheet,"startTime",n.scheduleStart());add(d,sheet,"endTime",n.scheduleEnd());add(d,sheet,"daylightSavingAdjust","NO");add(d,sheet,"excluded","NO");a.insertBefore(interval,before);}}
    private static void addAnnotation(Document d,Element a,String value,boolean reason){if(value==null||value.isBlank())return;Element wrapper=e(d,"annotation"),note=id(d,"Note");wrapper.appendChild(note);if(reason)add(d,note,"propertyName","operationalStatus");add(d,note,"purpose","REMARK");Element translated=e(d,"translatedNote"),ling=id(d,"LinguisticNote"),text=add(d,ling,"note",value.trim());text.setAttribute("lang","ENG");translated.appendChild(ling);note.appendChild(translated);Element status=BaselineAirportHeliportCatalog.first(a,"operationalStatus");a.insertBefore(d.createComment(reason?" Closure Reason ":" Note "),status);a.insertBefore(wrapper,status);}
    private static void clearOptional(Element a){for(String name:List.of("timeInterval","annotation"))for(Element x:new ArrayList<>(BaselineAirportHeliportCatalog.directChildren(a,name)))a.removeChild(x);for(Node n=a.getFirstChild();n!=null;){Node next=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE)a.removeChild(n);n=next;}}
    private static Element closedWrapper(Element feature){NodeList states=feature.getElementsByTagNameNS(CommonDigitalNotamBuilder.AIXM,"operationalStatus");for(int i=0;i<states.getLength();i++)if("CLOSED".equals(states.item(i).getTextContent().trim()))return(Element)states.item(i).getParentNode().getParentNode();return null;}
    private static void removeAvailabilityComments(Element slice){for(Node n=slice.getFirstChild();n!=null;){Node next=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE)slice.removeChild(n);n=next;}}
    private static void removeFeatureLabelComments(Element root){for(Node n=root.getFirstChild();n!=null;){Node next=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE&&n.getNodeValue()!=null&&n.getNodeValue().trim().matches("(?:RWY|FATO)\\s+.+"))root.removeChild(n);n=next;}}
    private static Element firstElement(Element p){for(Node n=p.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e)return e;return null;}
    private static Element directChild(Element p,String local){for(Node n=p.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e&&local.equals(e.getLocalName()))return e;throw new IllegalArgumentException("RWY.CLS 蓝图缺少 "+local);}
    private static void regenerateIds(Node root){if(root instanceof Element e&&e.hasAttributeNS(CommonDigitalNotamBuilder.GML,"id"))e.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","id_"+UUID.randomUUID());for(Node n=root.getFirstChild();n!=null;n=n.getNextSibling())regenerateIds(n);}
    private static void link(Element e,String uuid,String title){e.setAttributeNS(CommonDigitalNotamBuilder.XLINK,"xlink:href","urn:uuid:"+uuid);e.setAttributeNS(CommonDigitalNotamBuilder.XLINK,"xlink:title",title);}
    private static Element e(Document d,String local){return d.createElementNS(CommonDigitalNotamBuilder.AIXM,"aixm:"+local);}private static Element id(Document d,String local){Element e=e(d,local);e.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","id_"+UUID.randomUUID());return e;}private static Element add(Document d,Element p,String local,String value){Element e=e(d,local);e.setTextContent(value);p.appendChild(e);return e;}private static String date(String iso){return LocalDate.parse(iso).format(DateTimeFormatter.ofPattern("dd-MM"));}
}
