package com.example.digitalnotam.scenario.rwycls;

import com.example.digitalnotam.baseline.*;import com.example.digitalnotam.domain.Notam;import com.example.digitalnotam.scenario.common.QCodeDefaults;import com.example.digitalnotam.xml.CommonDigitalNotamBuilder;import org.w3c.dom.*;import java.time.*;import java.time.format.DateTimeFormatter;import java.util.*;

public final class RwyClsNotamProducer {
    private static final Set<String> UNPAVED=Set.of("CLAY","CORAL","EARTH","GRASS","GRAVEL","ICE","LATERITE","MACADAM","SAND","SNOW","WATER","OTHER");private final BaselineRunwayCatalog runways=new BaselineRunwayCatalog();private final BaselineAirportHeliportCatalog airports=new BaselineAirportHeliportCatalog();private final QCodeDefaults defaults=new QCodeDefaults();
    public void produce(Document d,Notam n)throws Exception{Instant start=Instant.parse(n.effectiveStart()),end=Instant.parse(n.effectiveEnd());var airport=airports.find(n.airport(),start,end);var target=runways.resolve(n.airport(),n.runwayUuid(),n.rwyTargetType(),n.runwayDirectionUuid(),start,end);String q="FATO".equals(target.runway().type())?"QFHLC":"QMRLC",qp[]=defaults.get(q);for(String[] x:new String[][]{{"affectedFIR",airport.firDesignator()},{"selectionCode",q},{"traffic",qp[0]},{"purpose",qp[1]},{"scope","A"},{"minimumFL","000"},{"maximumFL","999"},{"coordinates",coordinates(airport.latitude(),airport.longitude())},{"radius","005"},{"location",airport.locationIndicatorIcao().isBlank()?airport.designator().substring(0,2)+"XX":airport.locationIndicatorIcao()},{"effectiveStart",time(n.effectiveStart())},{"effectiveEnd",endTime(n.effectiveEnd())},{"estimatedEnd","NO"},{"permanent","NO"},{"text",itemE(d,airport,target)}})CommonDigitalNotamBuilder.setNotam(d,x[0],x[1]);}
    private static String itemE(Document d,BaselineAirportHeliportCatalog.AirportBaseline airport,BaselineRunwayCatalog.ResolvedTarget target){List<Element> closed=new ArrayList<>();for(Element s:CommonDigitalNotamBuilder.all(d,CommonDigitalNotamBuilder.AIXM,"operationalStatus"))if("CLOSED".equals(s.getTextContent().trim())&&s.getParentNode() instanceof Element a&&"ManoeuvringAreaAvailability".equals(a.getLocalName()))closed.add(a);if(closed.size()!=target.directions().size())throw new IllegalArgumentException("RWY.CLS CLOSED availability 数量与方向数量不一致");Element a=closed.get(0);StringBuilder out=new StringBuilder();if(airport.locationIndicatorIcao().isBlank())out.append(airportType(airport.type())).append(' ').append(airport.name().isBlank()?"LOCATED AT "+coordinates(airport.latitude(),airport.longitude()):airport.name()).append(System.lineSeparator());boolean unpaved=target.runway().surfaceCompositions().stream().anyMatch(x->UNPAVED.contains(x)||x.startsWith("OTHER:"));if(unpaved)out.append("UNPAVED ");out.append(target.runway().type()).append(' ').append(String.join("/",target.directions().stream().map(BaselineRunwayCatalog.RunwayDirectionBaseline::designator).toList())).append(" CLSD");String reason="";List<String> notes=new ArrayList<>();for(Element wrapper:BaselineAirportHeliportCatalog.directChildren(a,"annotation")){Element note=BaselineAirportHeliportCatalog.first(wrapper,"Note");if(note==null||!"REMARK".equals(BaselineAirportHeliportCatalog.text(note,"purpose")))continue;String value=BaselineAirportHeliportCatalog.text(note,"note");if("operationalStatus".equals(BaselineAirportHeliportCatalog.text(note,"propertyName")))reason=value;else if(!value.isBlank())notes.add(value);}if(!reason.isBlank())out.append(" DUE TO ").append(reason);out.append('.');for(String note:notes)out.append(System.lineSeparator()).append(finalizeNote(note));return out.toString().toUpperCase(Locale.ENGLISH);}
    private static String finalizeNote(String s){String v=s.trim();return v.endsWith(".")?v:v+".";}private static String airportType(String type){return switch(type){case"HP"->"HELIPORT";case"LS","OTHER"->"LANDING SITE";default->"AD";};}private static String time(String iso){return Instant.parse(iso).atZone(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("yyMMddHHmm"));}private static String endTime(String iso){ZonedDateTime z=Instant.parse(iso).atZone(ZoneOffset.UTC);return z.toLocalTime().equals(LocalTime.MIDNIGHT)?z.minusDays(1).format(DateTimeFormatter.ofPattern("yyMMdd"))+"2359":z.format(DateTimeFormatter.ofPattern("yyMMddHHmm"));}private static String coordinates(String lat,String lon){return coordinate(lat,2,Double.parseDouble(lat)<0?"S":"N")+coordinate(lon,3,Double.parseDouble(lon)<0?"W":"E");}private static String coordinate(String v,int width,String h){double x=Math.abs(Double.parseDouble(v));int d=(int)x,m=(int)Math.round((x-d)*60);if(m==60){d++;m=0;}return("%0"+width+"d%02d%s").formatted(d,m,h);}
}
