package com.example.digitalnotam.scenario.rwylim;

import com.example.digitalnotam.baseline.*;
import com.example.digitalnotam.domain.*;
import com.example.digitalnotam.scenario.common.schedule.EventScheduleSupport;
import com.example.digitalnotam.workflow.ScenarioBuilder;
import com.example.digitalnotam.xml.CommonDigitalNotamBuilder;
import org.w3c.dom.*;
import java.nio.file.Path;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public final class RwyLimScenarioBuilder implements ScenarioBuilder {
    private static final Path ROOT=Path.of("data","virtual data","Donlon_2025","Donlon","Digital NOTAM");
    private static final Map<String,String> TEMPLATES=Map.of("RESERV","DN_RWY.LIM_1_closed_except_for_takeoff.xml","CONDITIONAL","DN_RWY.LIM_2_conditional_for_PPR_1HR.xml","FORBID","DN_RWY.LIM_3_prohibited_for_night_VFR.xml","PERMIT","DN_RWY.LIM_4_additionally_allowed_for_training.xml");
    private static final String XSI="http://www.w3.org/2001/XMLSchema-instance";
    private static final Set<String> OPERATIONS=Set.of("LANDING","TAKEOFF","TOUCHGO","TRAIN_APPROACH","TAXIING","CROSSING","AIRSHOW","ALL");
    private static final Set<String> INTERPRETATIONS=Set.of("ABOVE","AT_OR_ABOVE","AT_OR_BELOW","BELOW");
    private static final Map<String,Set<String>> CONTROLLED=Map.of(
            "aircraftType",Set.of("LANDPLANE","SEAPLANE","AMPHIBIAN","HELICOPTER","GYROCOPTER","TILT_WING","STOL","GLIDER","HANGGLIDER","PARAGLIDER","ULTRA_LIGHT","BALLOON","UAV","ALL"),
            "aircraftEngine",Set.of("JET","PISTON","TURBOPROP","ALL"),"flightType",Set.of("OAT","GAT","ALL"),"flightRule",Set.of("IFR","VFR","ALL"),
            "flightStatus",Set.of("HEAD","STATE","HUM","HOSP","SAR","ALL","EMERGENCY"),"flightMilitary",Set.of("MIL","CIVIL","ALL"),
            "flightOrigin",Set.of("NTL","INTL","ALL","HOME_BASED"),"flightPurpose",Set.of("SCHEDULED","NON_SCHEDULED","PRIVATE","AIR_TRAINING","AIR_WORK","ALL","PARTICIPANT"));
    private final CommonDigitalNotamBuilder common=new CommonDigitalNotamBuilder();
    private final BaselineRunwayCatalog runways=new BaselineRunwayCatalog();
    private final BaselineAirportHeliportCatalog airports=new BaselineAirportHeliportCatalog();
    private final RwyLimScenarioValidator validator=new RwyLimScenarioValidator();
    public String scenario(){return "RWY.LIM";}

    public Document build(Notam n)throws Exception{
        if(!"EADD".equals(n.airport()))throw new IllegalArgumentException("RWY.LIM 第一版仅支持 EADD");
        List<AdLimRestriction> restrictions=restrictions(n);if(restrictions.isEmpty())throw new IllegalArgumentException("RWY.LIM 必须至少包含一个限制条件");
        String type=restrictions.get(0).limitationType();if(!TEMPLATES.containsKey(type)||restrictions.stream().anyMatch(x->!type.equals(x.limitationType())))throw new IllegalArgumentException("一次 RWY.LIM 通告中的所有限制条件必须使用相同的限制类型");
        for(var r:restrictions)validateInput(r,n);
        Instant start=Instant.parse(n.effectiveStart()),end=Instant.parse(n.effectiveEnd());var airport=airports.find(n.airport(),start,end);var target=runways.resolve(n.airport(),n.runwayUuid(),n.rwyTargetType(),n.runwayDirectionUuid(),start,end);
        Document d=common.populate(ROOT.resolve(TEMPLATES.get(type)),n);Element root=d.getDocumentElement(),event=CommonDigitalNotamBuilder.one(d,CommonDigitalNotamBuilder.EVENT,"Event"),template=null,eventAvailability=null;List<Node> remove=new ArrayList<>();
        for(Node node=root.getFirstChild();node!=null;node=node.getNextSibling())if(node instanceof Element member&&"hasMember".equals(member.getLocalName())){Element feature=firstElement(member);if(feature!=null&&"RunwayDirection".equals(feature.getLocalName())){if(template==null){template=(Element)member.cloneNode(true);eventAvailability=(Element)findEventAvailability(feature).getParentNode().cloneNode(true);}remove.add(member);}}
        if(template==null||eventAvailability==null)throw new IllegalArgumentException("RWY.LIM 蓝图缺少 RunwayDirection 事件 availability");for(Node x:remove)root.removeChild(x);removeFeatureComments(root);
        regenerateIds(d);String eventUuid=UUID.randomUUID().toString();event.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","uuid."+eventUuid);CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.GML,"identifier").setTextContent(eventUuid);CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"name").setTextContent(airport.designator()+" "+airport.name());link(CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"concernedAirspace"),airport.firUuid(),airport.firDesignator()+" FIR");link(CommonDigitalNotamBuilder.one(event,CommonDigitalNotamBuilder.EVENT,"concernedAirportHeliport"),airport.uuid(),airport.designator()+" "+airport.name());
        for(var direction:target.directions()){Element member=(Element)template.cloneNode(true),feature=firstElement(member);regenerateIds(feature);feature.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","uuid."+direction.uuid());CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.GML,"identifier").setTextContent(direction.uuid());Element slice=CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.AIXM,"RunwayDirectionTimeSlice");BaselineAirportHeliportCatalog.first(slice,"sequenceNumber").setTextContent(Integer.toString(direction.sequenceNumber()+1));for(Element x:new ArrayList<>(BaselineAirportHeliportCatalog.directChildren(slice,"availability")))slice.removeChild(x);removeDirectComments(slice);Element extension=directChild(slice,"extension");Node firstNormal=null;for(Element normal:direction.normalAvailabilities()){Node imported=d.importNode(normal,true);slice.insertBefore(imported,extension);if(firstNormal==null)firstNormal=imported;}Element wrapper=(Element)d.importNode(eventAvailability,true);regenerateIds(wrapper);Element availability=BaselineAirportHeliportCatalog.first(wrapper,"ManoeuvringAreaAvailability");clearEventAvailability(availability);BaselineAirportHeliportCatalog.first(availability,"operationalStatus").setTextContent("PERMIT".equals(type)?"OTHER:EXTENDED":"LIMITED");if(!"CONTINUOUS".equals(n.scheduleMode()))addSchedule(d,availability,n);addAnnotation(d,availability,n.reason(),true);addAnnotation(d,availability,n.remarks(),false);for(var r:restrictions)availability.appendChild(buildUsage(d,r));slice.insertBefore(wrapper,extension);if(firstNormal!=null)slice.insertBefore(d.createComment(" The baseline status of the runway direction "),firstNormal);slice.insertBefore(d.createComment(" The availability status of the runway direction during the event "),wrapper);link(CommonDigitalNotamBuilder.one(feature,CommonDigitalNotamBuilder.EVENT,"theEvent"),eventUuid,airport.designator()+" "+target.runway().designator()+" DNOTAM RWY.LIM");root.appendChild(d.createComment(" "+target.runway().type()+" "+direction.designator()+" "));root.appendChild(member);}
        CommonDigitalNotamBuilder.setNotam(d,"affectedFIR",airport.firDesignator());CommonDigitalNotamBuilder.setNotam(d,"location",airport.locationIndicatorIcao().isBlank()?airport.designator().substring(0,2)+"XX":airport.locationIndicatorIcao());excludeEventFromNormalAvailabilities(d,n);validator.validate(d,n,target);return d;
    }
    public void validate(Document d,Notam n){try{validator.validate(d,n,runways.resolve(n.airport(),n.runwayUuid(),n.rwyTargetType(),n.runwayDirectionUuid(),Instant.parse(n.effectiveStart()),Instant.parse(n.effectiveEnd())));}catch(RuntimeException e){throw e;}catch(Exception e){throw new IllegalArgumentException(e.getMessage(),e);}}
    private static void validateInput(AdLimRestriction r,Notam n){if(!OPERATIONS.contains(r.operation())&&!other(r.operation()))throw new IllegalArgumentException("operation 不在 RWY.LIM 受控值域中: "+r.operation());for(var x:Map.of("aircraftType",r.aircraftType(),"aircraftEngine",r.aircraftEngine(),"flightType",r.flightType(),"flightRule",r.flightRule(),"flightStatus",r.flightStatus(),"flightMilitary",r.flightMilitary(),"flightOrigin",r.flightOrigin(),"flightPurpose",r.flightPurpose()).entrySet())if(!x.getValue().isBlank()&&!CONTROLLED.get(x.getKey()).contains(x.getValue())&&!other(x.getValue()))throw new IllegalArgumentException(x.getKey()+" 不在受控值域中");if(!r.aircraftWingSpan().isBlank()&&(r.aircraftWingSpanUom().isBlank()||!INTERPRETATIONS.contains(r.aircraftWingSpanInterpretation())))throw new IllegalArgumentException("wingSpan 必须同时填写单位和 interpretation");if(!r.aircraftWeight().isBlank()&&(r.aircraftWeightUom().isBlank()||!INTERPRETATIONS.contains(r.aircraftWeightInterpretation())))throw new IllegalArgumentException("weight 必须同时填写单位和 interpretation");if(!r.pprValue().isBlank()&&!Set.of("HR","MIN","SEC").contains(r.pprUnit()))throw new IllegalArgumentException("PPR 单位必须为 HR/MIN/SEC");if(r.pprValue().isBlank()&&!r.pprDetails().isBlank())throw new IllegalArgumentException("PPR details 不能脱离 PPR 使用");}
    private static Element buildUsage(Document d,AdLimRestriction r){Element w=e(d,"usage"),u=id(d,"ManoeuvringAreaUsage");w.appendChild(u);add(d,u,"type",r.limitationType());Element p=add(d,u,"priorPermission",r.pprValue());if(r.pprValue().isBlank()){p.setAttributeNS(XSI,"xsi:nil","true");p.setAttribute("nilReason","inapplicable");}else p.setAttribute("uom",r.pprUnit());Element contact=e(d,"contact");contact.setAttributeNS(XSI,"xsi:nil","true");contact.setAttribute("nilReason","inapplicable");u.appendChild(contact);boolean hf=has(r.flightType(),r.flightRule(),r.flightStatus(),r.flightMilitary(),r.flightOrigin(),r.flightPurpose()),ha=has(r.aircraftType(),r.aircraftEngine(),r.aircraftWingSpan(),r.aircraftWeight());if(hf||ha){Element sw=e(d,"selection"),cc=id(d,"ConditionCombination");sw.appendChild(cc);u.appendChild(sw);add(d,cc,"logicalOperator",hf&&ha?"AND":"NONE");if(ha){Element aw=e(d,"aircraft"),a=id(d,"AircraftCharacteristic");aw.appendChild(a);cc.appendChild(aw);optional(d,a,"type",r.aircraftType());optional(d,a,"engine",r.aircraftEngine());measure(d,a,"wingSpan",r.aircraftWingSpan(),r.aircraftWingSpanUom());optional(d,a,"wingSpanInterpretation",r.aircraftWingSpanInterpretation());measure(d,a,"weight",r.aircraftWeight(),r.aircraftWeightUom());optional(d,a,"weightInterpretation",r.aircraftWeightInterpretation());}if(hf){Element fw=e(d,"flight"),f=id(d,"FlightCharacteristic");fw.appendChild(f);cc.appendChild(fw);optional(d,f,"type",r.flightType());optional(d,f,"rule",r.flightRule());optional(d,f,"status",r.flightStatus());optional(d,f,"military",r.flightMilitary());optional(d,f,"origin",r.flightOrigin());optional(d,f,"purpose",r.flightPurpose());}}if(!r.pprDetails().isBlank())u.appendChild(note(d,r.pprDetails(),"priorPermission"));add(d,u,"operation",r.operation());return w;}
    private static void clearEventAvailability(Element a){for(Node n=a.getFirstChild();n!=null;){Node next=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE||n instanceof Element e&&Set.of("timeInterval","annotation","usage").contains(e.getLocalName()))a.removeChild(n);n=next;}}
    private static void addSchedule(Document d,Element a,Notam n){Element before=BaselineAirportHeliportCatalog.first(a,"operationalStatus");a.insertBefore(d.createComment(" Schedule "),before);EventScheduleSupport.append(d,a,before,n,false);}
    private static void excludeEventFromNormalAvailabilities(Document d,Notam n){for(Element status:CommonDigitalNotamBuilder.all(d,CommonDigitalNotamBuilder.AIXM,"operationalStatus"))if("NORMAL".equals(status.getTextContent().trim()))EventScheduleSupport.append(d,(Element)status.getParentNode(),status,n,true);}
    private static void addAnnotation(Document d,Element a,String value,boolean reason){if(value==null||value.isBlank())return;Element before=BaselineAirportHeliportCatalog.first(a,"operationalStatus");a.insertBefore(d.createComment(reason?" Limitation Reason ":" Note "),before);a.insertBefore(note(d,value,reason?"operationalStatus":null),before);}
    private static Element note(Document d,String value,String property){Element w=e(d,"annotation"),n=id(d,"Note");w.appendChild(n);if(property!=null)add(d,n,"propertyName",property);add(d,n,"purpose","REMARK");Element tw=e(d,"translatedNote"),l=id(d,"LinguisticNote"),t=add(d,l,"note",value.trim());t.setAttribute("lang","ENG");tw.appendChild(l);n.appendChild(tw);return w;}
    private static Element findEventAvailability(Element f){NodeList states=f.getElementsByTagNameNS(CommonDigitalNotamBuilder.AIXM,"operationalStatus");for(int i=0;i<states.getLength();i++){Element s=(Element)states.item(i);if(Set.of("LIMITED","OTHER:EXTENDED").contains(s.getTextContent().trim()))return(Element)s.getParentNode();}throw new IllegalArgumentException("模板缺少事件 availability");}
    private static List<AdLimRestriction> restrictions(Notam n){return n.adLimRestrictions()==null?List.of():n.adLimRestrictions();}
    private static boolean other(String v){return v!=null&&v.matches("OTHER:[A-Z0-9][A-Z0-9_\\-]*");}private static boolean has(String...v){return Arrays.stream(v).anyMatch(x->x!=null&&!x.isBlank());}private static void optional(Document d,Element p,String n,String v){if(v!=null&&!v.isBlank())add(d,p,n,v);}private static void measure(Document d,Element p,String n,String v,String u){if(v.isBlank())return;Element x=add(d,p,n,v);x.setAttribute("uom",u);}
    private static Element firstElement(Element p){for(Node n=p.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e)return e;return null;}private static Element directChild(Element p,String local){for(Node n=p.getFirstChild();n!=null;n=n.getNextSibling())if(n instanceof Element e&&local.equals(e.getLocalName()))return e;throw new IllegalArgumentException("缺少 "+local);}
    private static void removeDirectComments(Element p){for(Node n=p.getFirstChild();n!=null;){Node x=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE)p.removeChild(n);n=x;}}private static void removeFeatureComments(Element p){for(Node n=p.getFirstChild();n!=null;){Node x=n.getNextSibling();if(n.getNodeType()==Node.COMMENT_NODE&&n.getNodeValue().trim().matches("(?:RWY|FATO)\\s+.+"))p.removeChild(n);n=x;}}
    private static void regenerateIds(Node r){if(r instanceof Element e&&e.hasAttributeNS(CommonDigitalNotamBuilder.GML,"id"))e.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","id_"+UUID.randomUUID());for(Node n=r.getFirstChild();n!=null;n=n.getNextSibling())regenerateIds(n);}private static void link(Element e,String u,String t){e.setAttributeNS(CommonDigitalNotamBuilder.XLINK,"xlink:href","urn:uuid:"+u);e.setAttributeNS(CommonDigitalNotamBuilder.XLINK,"xlink:title",t);}
    private static Element e(Document d,String l){return d.createElementNS(CommonDigitalNotamBuilder.AIXM,"aixm:"+l);}private static Element id(Document d,String l){Element e=e(d,l);e.setAttributeNS(CommonDigitalNotamBuilder.GML,"gml:id","id_"+UUID.randomUUID());return e;}private static Element add(Document d,Element p,String l,String v){Element e=e(d,l);e.setTextContent(v);p.appendChild(e);return e;}private static String date(String x){return LocalDate.parse(x).format(DateTimeFormatter.ofPattern("dd-MM"));}
}
