<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
const localInput=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)
const initialStart=new Date(Date.now()+30*60000),initialEnd=new Date(initialStart.getTime()+4*60*60000)
const items=ref([]), runways=ref([]), taxiways=ref([]), checkedIds=ref([]), query=ref(''), status=ref('ALL'), view=ref('list'), selected=ref(null), xml=ref(''), cnotam=ref(''), notice=ref('')
const form=reactive({scenario:'AD.CLS',fir:'EAAD',numberSeries:'A',numberDigits:'',title:'DONLON/INTL. OPERATIONAL EVENT',airport:'EADD',featureType:'AIRPORT_HELIPORT',condition:'AD closed.',selectedRunways:'',selectedTaxiways:'',eventDescription:'CLSD',reason:'SURFACE MAINTENANCE',remarks:'',effectiveStart:localInput(initialStart),effectiveEnd:localInput(initialEnd),latitude:'52.38',latitudeHemisphere:'N',longitude:'31.95',longitudeHemisphere:'W',radiusNm:'5',qCode:'QFALC',traffic:'IV',purpose:'NBO',scope:'A',lowerRestricted:false,upperRestricted:false,lowerMeters:'',upperMeters:'',scheduleMode:'CONTINUOUS',scheduleDays:['MON','TUE','WED','THU','FRI'],scheduleStart:localInput(initialStart).slice(11),scheduleEnd:localInput(initialEnd).slice(11)})
const scenarios=[['AD.CLS','机场关闭'],['AD.LIM','机场受限'],['RWY.CLS','跑道关闭'],['RWY.LIM','跑道受限'],['TWY.CLS','滑行道关闭'],['TWY.LIM','滑行道受限']]
const eventOptions=computed(()=>form.scenario.endsWith('.CLS')?[['CLSD','关闭（CLSD）']]:[['LIMITED','运行受限（LIMITED）']])
function scenarioChanged(){form.featureType=form.scenario.startsWith('AD.')?'AIRPORT_HELIPORT':form.scenario.startsWith('RWY.')?'RUNWAY':'TAXIWAY';form.eventDescription=form.scenario.endsWith('.CLS')?'CLSD':'LIMITED';form.qCode=form.scenario==='AD.CLS'?'QFALC':form.scenario==='RWY.CLS'?'QMRLC':form.scenario==='TWY.CLS'?'QMXLC':'QXXXX';if(form.scenario==='RWY.CLS'&&!form.selectedRunways)form.selectedRunways='09R/27L'}
async function loadRunways(){const r=await fetch(`/api/baseline/runways?airport=${form.airport}`);runways.value=r.ok?await r.json():[]}
async function loadTaxiways(){const r=await fetch(`/api/baseline/taxiways?airport=${form.airport}`);taxiways.value=r.ok?await r.json():[]}
async function loadAirportFeatures(){await Promise.all([loadRunways(),loadTaxiways()])}
function toggleTaxiway(code,checked){const selected=form.selectedTaxiways?form.selectedTaxiways.split(','):[];form.selectedTaxiways=(checked?[...new Set([...selected,code])]:selected.filter(x=>x!==code)).join(',')}
const eText=()=>{const subject=form.scenario.startsWith('AD.')?'AD':form.scenario==='RWY.CLS'?`RWY ${form.selectedRunways||'—'}`:form.scenario.startsWith('RWY.')?'RWY':form.scenario==='TWY.CLS'?`TWY ${form.selectedTaxiways.replaceAll(',',' ')||'—'}`:'TWY';const schedule=form.scheduleMode==='SCHEDULED'&&form.scheduleDays.length?` ${form.scheduleDays.join(' ')} ${form.scheduleStart.replace(':','')}-${form.scheduleEnd.replace(':','')} UTC`:'';return `${subject} ${form.eventDescription}${schedule}${form.reason?' DUE TO '+form.reason:''}${form.remarks?'. '+form.remarks:''}`.trim()}
const filtered=computed(()=>items.value.filter(n=>(status.value==='ALL'||n.status===status.value)&&(`${n.title}${n.airport}${n.number}`.toLowerCase().includes(query.value.toLowerCase()))))
const allFilteredSelected=computed(()=>filtered.value.length>0&&filtered.value.every(n=>checkedIds.value.includes(n.id)))
const stats=computed(()=>({all:items.value.length,draft:items.value.filter(x=>x.status==='DRAFT').length,published:items.value.filter(x=>x.status==='PUBLISHED').length}))
async function load(){items.value=await (await fetch('/api/notams')).json();checkedIds.value=checkedIds.value.filter(id=>items.value.some(n=>n.id===id))}
async function create(){const payload={...form,scheduleDay:form.scheduleDays.join(','),qCode:form.qCode.toUpperCase(),lowerMeters:form.lowerRestricted?form.lowerMeters:'',upperMeters:form.upperRestricted?form.upperMeters:'',effectiveStart:new Date(form.effectiveStart).toISOString(),effectiveEnd:new Date(form.effectiveEnd).toISOString()};const r=await fetch('/api/notams',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){notice.value=(await r.json()).message;return}notice.value='草稿创建成功';view.value='list';await load()}
async function publish(n){try{const r=await fetch(`/api/notams/${n.id}/publish`,{method:'POST'});if(!r.ok){const error=await r.json().catch(()=>({message:`发布失败（HTTP ${r.status}）`}));notice.value=error.message||`发布失败（HTTP ${r.status}）`;return}notice.value='通告发布成功';await load();selected.value=items.value.find(x=>x.id===n.id)}catch(e){notice.value=`发布失败：${e.message}`}}
async function remove(n){if(!window.confirm(`确定删除通告 ${n.number} 吗？此操作不可撤销。`))return;const r=await fetch(`/api/notams/${n.id}`,{method:'DELETE'});if(!r.ok){notice.value=(await r.json()).message;return}notice.value=`通告 ${n.number} 已删除`;selected.value=null;view.value='list';await load()}
function toggleAllFiltered(e){const visible=filtered.value.map(n=>n.id);checkedIds.value=e.target.checked?[...new Set([...checkedIds.value,...visible])]:checkedIds.value.filter(id=>!visible.includes(id))}
async function removeSelected(){const targets=items.value.filter(n=>checkedIds.value.includes(n.id));if(!targets.length)return;if(!window.confirm(`确定批量删除选中的 ${targets.length} 条通告吗？已发布通告的本地 XML 也会删除，此操作不可撤销。`))return;const failed=[];for(const n of targets){try{const r=await fetch(`/api/notams/${n.id}`,{method:'DELETE'});if(!r.ok){const error=await r.json().catch(()=>({}));failed.push(`${n.number}: ${error.message||`HTTP ${r.status}`}`)}}catch(e){failed.push(`${n.number}: ${e.message}`)}}checkedIds.value=[];await load();notice.value=failed.length?`批量删除完成，失败 ${failed.length} 条：${failed.join('；')}`:`已删除 ${targets.length} 条通告`}
async function detail(n){selected.value=n;xml.value=await (await fetch(`/api/notams/${n.id}/aixm`)).text();cnotam.value=n.status==='PUBLISHED'?await (await fetch(`/api/notams/${n.id}/cnotam`)).text():'发布后生成';view.value='detail'}
async function importXml(e){const file=e.target.files?.[0];if(!file)return;const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/xml'},body:await file.text()});if(!r.ok){notice.value='导入失败：'+(await r.json()).message;return}notice.value='Digital NOTAM XML导入并发布成功';await load();e.target.value=''}
const dt=s=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—'
const compact=s=>s?new Date(s).toISOString().slice(2,16).replace(/[-T:]/g,''):'—'
const fl=(meters,upper)=>meters!==undefined&&meters!==null&&String(meters).trim()!==''?String(Math.round(Number(meters)*3.28/100)).padStart(3,'0'):(upper?'999':'000')
const hasFg=n=>/^Q[WR]/.test((n?.qCode||form.qCode||'').toUpperCase())
const itemF=n=>hasFg(n)?`FL${n?.minimumFl||fl(form.lowerRestricted?form.lowerMeters:'',false)}`:'-'
const itemG=n=>hasFg(n)?`FL${n?.maximumFl||fl(form.upperRestricted?form.upperMeters:'',true)}`:'-'
const coordinate=(value,hem,width)=>{let v=Number(value);let d=Math.floor(v),m=Math.round((v-d)*60);if(m===60){d++;m=0}return String(d).padStart(width,'0')+String(m).padStart(2,'0')+hem}
const qLine=n=>{const x=n||form;return `${x.fir||'EAAD'}/${x.qCode||'QXXXX'}/${x.traffic||'IV'}/${x.purpose||'NBO'}/${x.scope||'A'}/${x.minimumFl||fl(x.lowerRestricted?x.lowerMeters:'',false)}/${x.maximumFl||fl(x.upperRestricted?x.upperMeters:'',true)}/${coordinate(x.latitude||0,x.latitudeHemisphere||'N',2)}${coordinate(x.longitude||0,x.longitudeHemisphere||'E',3)}/${String(x.radiusNm||0).padStart(3,'0')}`}
const weekdays=[['MON','星期一'],['TUE','星期二'],['WED','星期三'],['THU','星期四'],['FRI','星期五'],['SAT','星期六'],['SUN','星期日']]
const scheduleText=n=>{if((n?.scheduleMode||form.scheduleMode)==='CONTINUOUS')return '-';const days=n?n.scheduleDay.split(','):form.scheduleDays;return `${days.join(' ')} ${(n?.scheduleStart||form.scheduleStart).replace(':','')}-${(n?.scheduleEnd||form.scheduleEnd).replace(':','')} UTC`}
function scheduleModeChanged(){if(form.scheduleMode==='SCHEDULED'){form.scheduleStart=form.effectiveStart.slice(11,16);form.scheduleEnd=form.effectiveEnd.slice(11,16)}}
onMounted(()=>{load();loadAirportFeatures()})
</script>

<template>
<div class="shell">
  <aside><div class="brand"><span class="mark">DN</span><div><b>Digital NOTAM</b><small>AIXM 5.1.1</small></div></div>
    <nav><button :class="{active:view==='list'||view==='detail'}" @click="view='list'">▦ 通告管理</button><button :class="{active:view==='create'}" @click="view='create'">＋ 创建通告</button></nav>
    <div class="standard"><small>数据标准</small><strong>AIXM 5.1.1</strong><span>演示环境 · 北京时间</span></div>
  </aside>
  <main><header><div><h1>{{view==='create'?'创建数字通告':view==='detail'?'通告详情':'数字通告管理'}}</h1><p>航空情报数字化发布与管理演示平台</p></div><div class="summary-actions"><label class="danger">导入XML<input type="file" accept=".xml,application/xml" hidden @change="importXml"></label><button class="primary" @click="view='create'">＋ 新建通告</button></div></header>
    <div v-if="notice" class="notice" @click="notice=''">{{notice}} <span>×</span></div>
    <template v-if="view==='list'">
      <section class="stats"><article><span>全部通告</span><b>{{stats.all}}</b><i class="blue">总</i></article><article><span>待发布</span><b>{{stats.draft}}</b><i class="amber">草</i></article><article><span>已发布</span><b>{{stats.published}}</b><i class="green">发</i></article></section>
      <section class="panel"><div class="toolbar"><div class="search">⌕ <input v-model="query" placeholder="搜索编号、机场或标题"></div><select v-model="status"><option value="ALL">全部状态</option><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option></select><button class="danger batch-delete" :disabled="!checkedIds.length" @click="removeSelected">批量删除（{{checkedIds.length}}）</button></div>
        <table><thead><tr><th class="select-col"><input type="checkbox" :checked="allFilteredSelected" :disabled="!filtered.length" title="全选当前筛选结果" @change="toggleAllFiltered"></th><th>通告编号</th><th>标题 / 机场</th><th>要素类型</th><th>生效时间（UTC）</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="n in filtered" :key="n.id"><td class="select-col"><input v-model="checkedIds" type="checkbox" :value="n.id" :aria-label="`选择通告 ${n.number}`"></td><td><b>{{n.number}}</b></td><td><strong>{{n.title}}</strong><small>{{n.airport}} · {{n.condition}}</small></td><td>{{n.featureType}}</td><td>{{dt(n.effectiveStart)}}<small>至 {{dt(n.effectiveEnd)}}</small></td><td><span class="pill" :class="n.status.toLowerCase()">{{n.status==='DRAFT'?'草稿':'已发布'}}</span></td><td><button class="link" @click="detail(n)">查看</button><button v-if="n.status==='DRAFT'" class="link publish" @click="publish(n)">发布</button><button class="link delete" @click="remove(n)">删除</button></td></tr></tbody></table>
      </section>
    </template>
    <section v-else-if="view==='create'" class="panel form">
      <div class="section-title"><b>Digital NOTAM</b><span>按ICAO NOTAM的Q行及A–G项填写和预览</span></div>
      <div class="notam-fields"><div class="field-row q"><b>Q)</b><span>{{qLine()}}</span></div><div class="field-row"><b>A)</b><span>{{form.airport}}</span></div><div class="field-row"><b>B)</b><span>{{compact(form.effectiveStart)}} UTC</span></div><div class="field-row"><b>C)</b><span>{{compact(form.effectiveEnd)}} UTC</span></div><div class="field-row"><b>D)</b><span>{{scheduleText()}}</span></div><div class="field-row"><b>E)</b><span>{{eText()||'待填写'}}</span></div><div class="field-row"><b>F)</b><span>{{itemF()}}</span></div><div class="field-row"><b>G)</b><span>{{itemG()}}</span></div></div>
      <div class="grid">
        <div class="field-group wide"><h3>通告业务设置</h3><div class="group-grid business-grid"><label>业务场景 *<select v-model="form.scenario" @change="scenarioChanged"><option v-for="s in scenarios" :key="s[0]" :value="s[0]">{{s[0]}} — {{s[1]}}</option></select></label><label>编号系列 *<select v-model="form.numberSeries"><option value="A">A — 国际分发</option><option value="C">C — 国内分发</option><option value="D">D — 地区内分发</option></select></label><label>编号数字<input v-model="form.numberDigits" maxlength="4" placeholder="留空自动分配"></label><label>通告标题 *<input v-model="form.title"></label></div></div>
        <div class="field-group wide"><h3>Q 行</h3><div class="group-grid q-grid"><label>FIR *<select v-model="form.fir"><option value="EAAD">EAAD</option></select></label><label>Q-CODE *<input v-model="form.qCode" maxlength="5" placeholder="例如 QFALC"></label><label>TRAFFIC *<select v-model="form.traffic"><option>I</option><option>V</option><option>IV</option></select></label><label>PURPOSE *<select v-model="form.purpose"><option>N</option><option>B</option><option>O</option><option>NB</option><option>NO</option><option>BO</option><option>NBO</option></select></label><label>SCOPE *<select v-model="form.scope"><option>A</option><option>E</option><option>AE</option></select></label><label>纬度（十进制度）<div class="inline-input"><input v-model="form.latitude" type="number" min="0" max="90" step="any"><select v-model="form.latitudeHemisphere"><option>N</option><option>S</option></select></div></label><label>经度（十进制度）<div class="inline-input"><input v-model="form.longitude" type="number" min="0" max="180" step="any"><select v-model="form.longitudeHemisphere"><option>E</option><option>W</option></select></div></label><label>影响半径（NM）<input v-model="form.radiusNm" type="number" min="0" max="999"></label></div>
          <div class="limit-grid"><label>下限类型<select v-model="form.lowerRestricted"><option :value="false">无限制（000）</option><option :value="true">指定米数</option></select></label><label>下限高度（米）<input v-model="form.lowerMeters" type="number" min="0" max="16000" :disabled="!form.lowerRestricted"><small>换算结果：FL{{fl(form.lowerRestricted?form.lowerMeters:'',false)}}</small></label><label>上限类型<select v-model="form.upperRestricted"><option :value="false">无限制（999）</option><option :value="true">指定米数</option></select></label><label>上限高度（米）<input v-model="form.upperMeters" type="number" min="0" max="16000" :disabled="!form.upperRestricted"><small>换算结果：FL{{fl(form.upperRestricted?form.upperMeters:'',true)}}</small></label></div>
        </div>
        <label>A 项：机场<select v-model="form.airport" @change="loadAirportFeatures"><option value="EADD">EADD — DONLON/INTL.</option></select></label><label>B 项：开始时间 *<input v-model="form.effectiveStart" type="datetime-local"></label><label>C 项：结束时间 *<input v-model="form.effectiveEnd" type="datetime-local"></label>
        <div v-if="form.scenario==='RWY.CLS'" class="field-group wide"><h3>RWY.CLS 场景数据</h3><div class="runway-options"><label v-for="r in runways" :key="r.designator" :class="{unsupported:!r.supported}"><input type="checkbox" :checked="form.selectedRunways===r.designator" :disabled="!r.supported" @change="form.selectedRunways=$event.target.checked?r.designator:''"><span><b>{{r.designator}}</b><small>{{r.supported?'关闭该跑道的全部方向':'当前RWY.CLS模板未支持'}}</small></span></label></div></div>
        <div v-if="form.scenario==='TWY.CLS'" class="field-group wide"><h3>TWY.CLS 场景数据</h3><div class="runway-options"><label v-for="t in taxiways" :key="t.designator"><input type="checkbox" :checked="form.selectedTaxiways.split(',').includes(t.designator)" @change="toggleTaxiway(t.designator,$event.target.checked)"><span><b>TWY {{t.designator}}</b><small>关闭整条滑行道</small></span></label></div><small>滑行道编号来自所选机场的 AIXM Baseline 数据。</small></div>
        <div class="field-group wide"><h3>D 项：时间计划（UTC）</h3><div class="group-grid schedule"><label>生效方式<select v-model="form.scheduleMode" @change="scheduleModeChanged"><option value="CONTINUOUS">整个B–C有效期连续生效</option><option value="SCHEDULED">按D项时间计划生效</option></select></label><template v-if="form.scheduleMode==='SCHEDULED'"><div class="weekday-picker"><span>适用星期 *</span><label v-for="day in weekdays" :key="day[0]"><input v-model="form.scheduleDays" type="checkbox" :value="day[0]">{{day[1]}}</label></div><label>开始时间 *<input v-model="form.scheduleStart" type="time"></label><label>结束时间 *<input v-model="form.scheduleEnd" type="time"></label></template></div><small v-if="form.scheduleMode==='CONTINUOUS'">连续模式不会在事件关闭状态中生成Timesheet。</small><small v-else>每个选中的星期将分别生成一个Timesheet；不使用WORK_DAY或节假日代码。</small></div>
        <div class="field-group wide"><h3>E 项：结构化事件数据</h3><div class="group-grid structured-e"><label>事件 *<select v-model="form.eventDescription"><option v-for="option in eventOptions" :key="option[0]" :value="option[0]">{{option[1]}}</option></select></label><label>原因 *<input v-model="form.reason" placeholder="例如 SURFACE MAINTENANCE"></label><label>备注<input v-model="form.remarks" placeholder="可选，例如 RUBBER REMOVAL"></label></div></div>
        <label class="wide">E 项：结构化生成结果<textarea :value="eText()" readonly></textarea></label><label>F 项：下限（仅QW/QR）<input :value="itemF()" readonly></label><label>G 项：上限（仅QW/QR）<input :value="itemG()" readonly></label>
      </div>
      <div class="actions"><button @click="view='list'">取消</button><button class="primary" @click="create">保存为草稿</button></div>
    </section>
    <section v-else class="detail">
      <div class="panel summary"><div><span class="pill" :class="selected.status.toLowerCase()">{{selected.status==='DRAFT'?'草稿':'已发布'}}</span><h2>{{selected.title}}</h2><p>{{selected.number}} · {{selected.airport}}</p></div><div class="summary-actions"><button class="danger" @click="remove(selected)">删除通告</button><button v-if="selected.status==='DRAFT'" class="primary" @click="publish(selected)">发布通告</button></div></div>
      <section class="panel notam-card"><h3>NOTAM</h3><div class="notam-fields"><div class="field-row q"><b>Q)</b><span>{{qLine(selected)}}</span></div><div class="field-row"><b>A)</b><span>{{selected.airport}}</span></div><div class="field-row"><b>B)</b><span>{{compact(selected.effectiveStart)}} UTC</span></div><div class="field-row"><b>C)</b><span>{{compact(selected.effectiveEnd)}} UTC</span></div><div class="field-row"><b>D)</b><span>{{scheduleText(selected)}}</span></div><div class="field-row"><b>E)</b><span>{{selected.condition}}</span></div><div class="field-row"><b>F)</b><span>{{itemF(selected)}}</span></div><div class="field-row"><b>G)</b><span>{{itemG(selected)}}</span></div></div></section>
      <div class="cols"><section class="panel info"><h3>通告信息</h3><dl><div><dt>场景 / 航空要素</dt><dd>{{selected.scenario}} / {{selected.featureType}}</dd></div><div><dt>有效期</dt><dd>{{dt(selected.effectiveStart)}} 至<br>{{dt(selected.effectiveEnd)}}</dd></div><div><dt>坐标</dt><dd>{{selected.latitude}}, {{selected.longitude}} / {{selected.radiusNm}} NM</dd></div></dl><h3>CNOTAM转换结果</h3><pre class="cnotam">{{cnotam}}</pre></section><section class="panel xml"><h3>AIXM 5.1.1 XML预览</h3><pre>{{xml}}</pre></section></div>
    </section>
  </main>
</div>
</template>
