<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
const localInput=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16)
const initialStart=new Date(Date.now()+30*60000),initialEnd=new Date(initialStart.getTime()+4*60*60000)
const items=ref([]), airports=ref([]), runways=ref([]), taxiways=ref([]), checkedIds=ref([]), query=ref(''), status=ref('ALL'), view=ref('list'), selected=ref(null), xml=ref(''), cnotam=ref(''), notice=ref(''), editingId=ref(null)
const form=reactive({scenario:'AD.CLS',fir:'EAAD',numberSeries:'A',numberDigits:'',title:'DONLON/INTL. OPERATIONAL EVENT',airport:'EADD',featureType:'AIRPORT_HELIPORT',condition:'AD closed.',selectedRunways:'',selectedTaxiways:'',eventDescription:'CLSD',reason:'SURFACE MAINTENANCE',remarks:'',effectiveStart:localInput(initialStart),effectiveEnd:localInput(initialEnd),latitude:'52.37166667',latitudeHemisphere:'N',longitude:'31.94944444',longitudeHemisphere:'W',radiusNm:'5',qCode:'QFALC',traffic:'IV',purpose:'NBO',scope:'A',lowerRestricted:false,upperRestricted:false,lowerMeters:'',upperMeters:'',scheduleMode:'CONTINUOUS',scheduleDays:['MON','TUE','WED','THU','FRI'],scheduleStart:localInput(initialStart).slice(11),scheduleEnd:localInput(initialEnd).slice(11),scheduleStartDate:localInput(initialStart).slice(0,10),scheduleEndDate:localInput(initialEnd).slice(0,10),qOverrideReason:'',qOverrideOperator:'',qOverrideAt:'',limitationType:'RESERV',operation:'ALL',operationOther:'',includeAircraft:false,includeFlight:false,includePpr:false,flightType:'',flightTypeOther:'',flightRule:'',flightRuleOther:'',flightStatus:'',flightStatusOther:'',flightMilitary:'',flightMilitaryOther:'',flightOrigin:'',flightOriginOther:'',flightPurpose:'',flightPurposeOther:'',aircraftType:'',aircraftTypeOther:'',aircraftEngine:'',aircraftEngineOther:'',aircraftWingSpan:'',aircraftWingSpanUom:'M',aircraftWingSpanInterpretation:'',aircraftWeight:'',aircraftWeightUom:'T',aircraftWeightInterpretation:'',pprValue:'',pprUnit:'HR',pprDetails:''})
const newRestriction=()=>({operation:'ALL',operationOther:'',includeAircraft:false,includeFlight:false,includePpr:false,flightType:'',flightTypeOther:'',flightRule:'',flightRuleOther:'',flightStatus:'',flightStatusOther:'',flightMilitary:'',flightMilitaryOther:'',flightOrigin:'',flightOriginOther:'',flightPurpose:'',flightPurposeOther:'',aircraftType:'',aircraftTypeOther:'',aircraftEngine:'',aircraftEngineOther:'',aircraftWingSpan:'',aircraftWingSpanUom:'M',aircraftWingSpanInterpretation:'',aircraftWeight:'',aircraftWeightUom:'T',aircraftWeightInterpretation:'',pprValue:'',pprUnit:'HR',pprDetails:''})
const restrictions=ref([newRestriction()])
const addRestriction=()=>restrictions.value.push(newRestriction())
const removeRestriction=index=>{if(restrictions.value.length>1)restrictions.value.splice(index,1)}
const moveRestriction=(index,offset)=>{const target=index+offset;if(target<0||target>=restrictions.value.length)return;const [item]=restrictions.value.splice(index,1);restrictions.value.splice(target,0,item)}
const scenarios=[['AD.CLS','机场关闭'],['AD.LIM','机场受限'],['RWY.CLS','跑道关闭'],['RWY.LIM','跑道受限'],['TWY.CLS','滑行道关闭'],['TWY.LIM','滑行道受限']]
const eventOptions=computed(()=>form.scenario.endsWith('.CLS')?[['CLSD','关闭（CLSD）']]:[['LIMITED','运行受限（LIMITED）']])
function scenarioChanged(){form.featureType=form.scenario.startsWith('AD.')?'AIRPORT_HELIPORT':form.scenario.startsWith('RWY.')?'RUNWAY':'TAXIWAY';form.eventDescription=form.scenario.endsWith('.CLS')?'CLSD':'LIMITED';form.qCode=form.scenario==='AD.CLS'?'QFALC':form.scenario==='AD.LIM'?'QFALT':form.scenario==='RWY.CLS'?'QMRLC':form.scenario==='TWY.CLS'?'QMXLC':'QXXXX';if(form.scenario==='RWY.CLS'&&!form.selectedRunways)form.selectedRunways='09R/27L'}
async function loadRunways(){const r=await fetch(`/api/baseline/runways?airport=${form.airport}`);runways.value=r.ok?await r.json():[]}
async function loadTaxiways(){const r=await fetch(`/api/baseline/taxiways?airport=${form.airport}`);taxiways.value=r.ok?await r.json():[]}
async function loadAirports(){const r=await fetch('/api/baseline/airports');airports.value=r.ok?await r.json():[];airportChanged()}
function airportChanged(){const a=airports.value.find(x=>x.designator===form.airport);if(!a)return;form.fir=a.fir;form.qCode=form.scenario==='AD.LIM'?(a.type==='HP'?'QFPLT':'QFALT'):(a.type==='HP'?'QFPLC':'QFALC');form.traffic='IV';form.purpose=a.type==='HP'&&form.scenario==='AD.LIM'?'BO':'NBO';form.scope='A';form.lowerRestricted=false;form.upperRestricted=false;form.latitude=String(Math.abs(Number(a.latitude)));form.latitudeHemisphere=Number(a.latitude)<0?'S':'N';form.longitude=String(Math.abs(Number(a.longitude)));form.longitudeHemisphere=Number(a.longitude)<0?'W':'E';form.radiusNm='5';loadAirportFeatures()}
async function loadAirportFeatures(){await Promise.all([loadRunways(),loadTaxiways()])}
function toggleTaxiway(code,checked){const selected=form.selectedTaxiways?form.selectedTaxiways.split(','):[];form.selectedTaxiways=(checked?[...new Set([...selected,code])]:selected.filter(x=>x!==code)).join(',')}
const eText=()=>{const subject=form.scenario.startsWith('AD.')?'AD':form.scenario==='RWY.CLS'?`RWY ${form.selectedRunways||'—'}`:form.scenario.startsWith('RWY.')?'RWY':form.scenario==='TWY.CLS'?`TWY ${form.selectedTaxiways.replaceAll(',',' ')||'—'}`:'TWY';const schedule=form.scheduleMode==='SCHEDULED'&&form.scheduleDays.length?` ${form.scheduleDays.join(' ')} ${form.scheduleStart.replace(':','')}-${form.scheduleEnd.replace(':','')} UTC`:'';return `${subject} ${form.eventDescription}${schedule}${form.reason?' DUE TO '+form.reason:''}${form.remarks?'. '+form.remarks:''}`.trim()}
const filtered=computed(()=>items.value.filter(n=>(status.value==='ALL'||n.status===status.value)&&(`${n.title}${n.airport}${n.number}`.toLowerCase().includes(query.value.toLowerCase()))))
const allFilteredSelected=computed(()=>filtered.value.length>0&&filtered.value.every(n=>checkedIds.value.includes(n.id)))
const stats=computed(()=>({all:items.value.length,draft:items.value.filter(x=>x.status==='DRAFT').length,published:items.value.filter(x=>x.status==='PUBLISHED').length}))
async function load(){items.value=await (await fetch('/api/notams')).json();checkedIds.value=checkedIds.value.filter(id=>items.value.some(n=>n.id===id))}
const otherValue=(value,other)=>value==='OTHER'?(other.trim()?`OTHER:${other.trim().toUpperCase().replaceAll(' ','_')}`:''):value
const decodedValue=value=>value?.startsWith('OTHER:')?['OTHER',value.slice(6).replaceAll('_',' ')]:[value||'','']
function restrictionFrom(value){const r={...newRestriction(),...value};for(const name of ['operation','aircraftType','aircraftEngine','flightType','flightRule','flightStatus','flightMilitary','flightOrigin','flightPurpose']){const [code,other]=decodedValue(value[name]);r[name]=code;r[`${name}Other`]=other}r.includeAircraft=!![r.aircraftType,r.aircraftEngine,r.aircraftWingSpan,r.aircraftWeight].some(Boolean);r.includeFlight=!![r.flightType,r.flightRule,r.flightStatus,r.flightMilitary,r.flightOrigin,r.flightPurpose].some(Boolean);r.includePpr=!!r.pprValue;return r}
function startNew(){editingId.value=null;restrictions.value=[newRestriction()];view.value='create'}
function editDraft(n){if(n.status!=='DRAFT')return;editingId.value=n.id;Object.assign(form,n,{numberSeries:n.number.slice(0,1),numberDigits:n.number.match(/^[A-Z](\d+)\//)?.[1]||'',effectiveStart:localInput(new Date(n.effectiveStart)),effectiveEnd:localInput(new Date(n.effectiveEnd)),lowerRestricted:!!n.lowerMeters,upperRestricted:!!n.upperMeters,scheduleDays:(n.scheduleDay||'').split(',').filter(Boolean),limitationType:n.limitationType||n.restrictions?.[0]?.limitationType||'RESERV'});restrictions.value=n.restrictions?.length?n.restrictions.map(restrictionFrom):[restrictionFrom(n)];loadAirportFeatures();view.value='create'}
function encodedRestriction(source,index){if(source.operation==='OTHER'&&!source.operationOther.trim())throw new Error(`限制条件 ${index+1}：OTHER Operation 必须填写具体字符`);if(source.includeAircraft&&![source.aircraftType,source.aircraftEngine,source.aircraftWingSpan,source.aircraftWeight].some(Boolean))throw new Error(`限制条件 ${index+1}：Aircraft 至少填写一项限制`);if(source.includeFlight&&![source.flightType,source.flightRule,source.flightStatus,source.flightMilitary,source.flightOrigin,source.flightPurpose].some(Boolean))throw new Error(`限制条件 ${index+1}：Flight 至少填写一项限制`);for(const name of ['aircraftType','aircraftEngine','flightType','flightRule','flightStatus','flightMilitary','flightOrigin','flightPurpose'])if(source[name]==='OTHER'&&!source[`${name}Other`].trim())throw new Error(`限制条件 ${index+1}：${name} 的 OTHER 必须填写具体字符`);if(source.includePpr&&!source.pprValue)throw new Error(`限制条件 ${index+1}：PPR 必须填写时间`);const result={...source,limitationType:form.limitationType,operation:otherValue(source.operation,source.operationOther)};for(const name of ['aircraftType','aircraftEngine','flightType','flightRule','flightStatus','flightMilitary','flightOrigin','flightPurpose'])result[name]=otherValue(source[name],source[`${name}Other`]);if(!source.includeAircraft)for(const name of ['aircraftType','aircraftEngine','aircraftWingSpan','aircraftWingSpanUom','aircraftWingSpanInterpretation','aircraftWeight','aircraftWeightUom','aircraftWeightInterpretation'])result[name]='';if(!source.includeFlight)for(const name of ['flightType','flightRule','flightStatus','flightMilitary','flightOrigin','flightPurpose'])result[name]='';if(!source.includePpr)for(const name of ['pprValue','pprUnit','pprDetails'])result[name]='';return result}
async function create(){const payload={...form,scheduleDay:form.scheduleDays.join(','),qCode:form.qCode.toUpperCase(),qOverrideAt:form.qOverrideReason?new Date().toISOString():'',lowerMeters:form.lowerRestricted?form.lowerMeters:'',upperMeters:form.upperRestricted?form.upperMeters:'',effectiveStart:new Date(form.effectiveStart).toISOString(),effectiveEnd:new Date(form.effectiveEnd).toISOString()};if(form.scenario==='AD.LIM')try{payload.restrictions=restrictions.value.map(encodedRestriction)}catch(e){notice.value=e.message;return}const updating=!!editingId.value;const r=await fetch(updating?`/api/notams/${editingId.value}`:'/api/notams',{method:updating?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok){notice.value=(await r.json()).message;return}notice.value=updating?'草稿已更新':'草稿创建成功';editingId.value=null;view.value='list';await load()}
async function publish(n){try{const r=await fetch(`/api/notams/${n.id}/publish`,{method:'POST'});if(!r.ok){const error=await r.json().catch(()=>({message:`发布失败（HTTP ${r.status}）`}));notice.value=error.message||`发布失败（HTTP ${r.status}）`;return}notice.value='通告发布成功';await load();selected.value=items.value.find(x=>x.id===n.id)}catch(e){notice.value=`发布失败：${e.message}`}}
async function remove(n){if(!window.confirm(`确定删除通告 ${n.number} 吗？此操作不可撤销。`))return;const r=await fetch(`/api/notams/${n.id}`,{method:'DELETE'});if(!r.ok){notice.value=(await r.json()).message;return}notice.value=`通告 ${n.number} 已删除`;selected.value=null;view.value='list';await load()}
function toggleAllFiltered(e){const visible=filtered.value.map(n=>n.id);checkedIds.value=e.target.checked?[...new Set([...checkedIds.value,...visible])]:checkedIds.value.filter(id=>!visible.includes(id))}
async function removeSelected(){const targets=items.value.filter(n=>checkedIds.value.includes(n.id));if(!targets.length)return;if(!window.confirm(`确定批量删除选中的 ${targets.length} 条通告吗？已发布通告的本地 XML 也会删除，此操作不可撤销。`))return;const failed=[];for(const n of targets){try{const r=await fetch(`/api/notams/${n.id}`,{method:'DELETE'});if(!r.ok){const error=await r.json().catch(()=>({}));failed.push(`${n.number}: ${error.message||`HTTP ${r.status}`}`)}}catch(e){failed.push(`${n.number}: ${e.message}`)}}checkedIds.value=[];await load();notice.value=failed.length?`批量删除完成，失败 ${failed.length} 条：${failed.join('；')}`:`已删除 ${targets.length} 条通告`}
async function detail(n){selected.value=n;xml.value=await (await fetch(`/api/notams/${n.id}/aixm`)).text();cnotam.value=n.status==='PUBLISHED'?await (await fetch(`/api/notams/${n.id}/cnotam`)).text():'发布后生成';view.value='detail'}
async function importXml(e){const file=e.target.files?.[0];if(!file)return;const r=await fetch('/api/import',{method:'POST',headers:{'Content-Type':'application/xml'},body:await file.text()});if(!r.ok){notice.value='导入失败：'+(await r.json()).message;return}notice.value='Digital NOTAM XML导入并发布成功';await load();e.target.value=''}
const dt=s=>s?new Date(s).toLocaleString('zh-CN',{hour12:false}):'—'
const compact=s=>s?new Date(s).toISOString().slice(2,16).replace(/[-T:]/g,''):'—'
const fl=(meters,upper)=>meters!==undefined&&meters!==null&&String(meters).trim()!==''?String(Math.round(Number(meters)*3.28/100)).padStart(3,'0'):(upper?'999':'000')
const hasFg=n=>/^Q[WR]/.test((n?.qCode||form.qCode||'').toUpperCase())
const itemF=n=>hasFg(n)?`FL${n?.minimumFl||fl(form.lowerRestricted?form.lowerMeters:'',false)}`:'-'
const itemG=n=>hasFg(n)?`FL${n?.maximumFl||fl(form.upperRestricted?form.upperMeters:'',true)}`:'-'
const coordinate=(value,hem,width)=>{let v=Number(value);let d=Math.floor(v),m=Math.round((v-d)*60);if(m===60){d++;m=0}return String(d).padStart(width,'0')+String(m).padStart(2,'0')+hem}
const qLine=n=>{const x=n||form;return `${x.fir||'EAAD'}/${x.qCode||'QXXXX'}/${x.traffic||'IV'}/${x.purpose||'NBO'}/${x.scope||'A'}/${x.minimumFl||fl(x.lowerRestricted?x.lowerMeters:'',false)}/${x.maximumFl||fl(x.upperRestricted?x.upperMeters:'',true)}/${coordinate(x.latitude||0,x.latitudeHemisphere||'N',2)}${coordinate(x.longitude||0,x.longitudeHemisphere||'E',3)}/${String(x.radiusNm||0).padStart(3,'0')}`}
const weekdays=[['MON','星期一'],['TUE','星期二'],['WED','星期三'],['THU','星期四'],['FRI','星期五'],['SAT','星期六'],['SUN','星期日']]
const scheduleText=n=>{const mode=n?.scheduleMode||form.scheduleMode;if(mode==='CONTINUOUS')return '-';const start=(n?.scheduleStart||form.scheduleStart).replace(':',''),end=(n?.scheduleEnd||form.scheduleEnd).replace(':','');if(mode==='DAILY')return `DAILY ${start}-${end} UTC`;if(mode==='DATES')return `${n?.scheduleStartDate||form.scheduleStartDate} - ${n?.scheduleEndDate||form.scheduleEndDate} ${start}-${end} UTC`;const days=n?n.scheduleDay.split(','):form.scheduleDays;return `${days.join(' ')} ${start}-${end} UTC`}
function scheduleModeChanged(){if(form.scheduleMode==='SCHEDULED'){form.scheduleStart=form.effectiveStart.slice(11,16);form.scheduleEnd=form.effectiveEnd.slice(11,16)}}
onMounted(()=>{load();loadAirports()})
</script>

<template>
<div class="shell">
  <aside><div class="brand"><span class="mark">DN</span><div><b>Digital NOTAM</b><small>AIXM 5.1.1</small></div></div>
    <nav><button :class="{active:view==='list'||view==='detail'}" @click="view='list'">▦ 通告管理</button><button :class="{active:view==='create'}" @click="startNew">＋ 创建通告</button></nav>
    <div class="standard"><small>数据标准</small><strong>AIXM 5.1.1</strong><span>演示环境 · 北京时间</span></div>
  </aside>
  <main><header><div><h1>{{view==='create'?(editingId?'编辑数字通告':'创建数字通告'):view==='detail'?'通告详情':'数字通告管理'}}</h1><p>航空情报数字化发布与管理演示平台</p></div><div class="summary-actions"><label class="danger">导入XML<input type="file" accept=".xml,application/xml" hidden @change="importXml"></label><button class="primary" @click="startNew">＋ 新建通告</button></div></header>
    <div v-if="notice" class="notice" @click="notice=''">{{notice}} <span>×</span></div>
    <template v-if="view==='list'">
      <section class="stats"><article><span>全部通告</span><b>{{stats.all}}</b><i class="blue">总</i></article><article><span>待发布</span><b>{{stats.draft}}</b><i class="amber">草</i></article><article><span>已发布</span><b>{{stats.published}}</b><i class="green">发</i></article></section>
      <section class="panel"><div class="toolbar"><div class="search">⌕ <input v-model="query" placeholder="搜索编号、机场或标题"></div><select v-model="status"><option value="ALL">全部状态</option><option value="DRAFT">草稿</option><option value="PUBLISHED">已发布</option></select><button class="danger batch-delete" :disabled="!checkedIds.length" @click="removeSelected">批量删除（{{checkedIds.length}}）</button></div>
        <table><thead><tr><th class="select-col"><input type="checkbox" :checked="allFilteredSelected" :disabled="!filtered.length" title="全选当前筛选结果" @change="toggleAllFiltered"></th><th>通告编号</th><th>标题 / 机场</th><th>要素类型</th><th>生效时间（UTC）</th><th>状态</th><th>操作</th></tr></thead><tbody><tr v-for="n in filtered" :key="n.id"><td class="select-col"><input v-model="checkedIds" type="checkbox" :value="n.id" :aria-label="`选择通告 ${n.number}`"></td><td><b>{{n.number}}</b></td><td><strong>{{n.title}}</strong><small>{{n.airport}} · {{n.condition}}</small></td><td>{{n.featureType}}</td><td>{{dt(n.effectiveStart)}}<small>至 {{dt(n.effectiveEnd)}}</small></td><td><span class="pill" :class="n.status.toLowerCase()">{{n.status==='DRAFT'?'草稿':'已发布'}}</span></td><td><button class="link" @click="detail(n)">查看</button><button v-if="n.status==='DRAFT'" class="link publish" @click="publish(n)">发布</button><button class="link delete" @click="remove(n)">删除</button></td></tr></tbody></table>
      </section>
    </template>
    <section v-else-if="view==='create'" class="panel form">
      <div class="section-title"><b>Digital NOTAM</b><span>按ICAO NOTAM的Q行及A–G项填写和预览</span></div>
      <div class="grid">
        <div class="field-group wide"><h3>通告业务设置</h3><div class="group-grid business-grid"><label>业务场景 *<select v-model="form.scenario" @change="scenarioChanged"><option v-for="s in scenarios" :key="s[0]" :value="s[0]">{{s[0]}} — {{s[1]}}</option></select></label><label>编号系列 *<select v-model="form.numberSeries" :disabled="!!editingId"><option value="A">A — 国际分发</option><option value="C">C — 国内分发</option><option value="D">D — 地区内分发</option></select></label><label>编号数字<input v-model="form.numberDigits" maxlength="4" placeholder="留空自动分配" :disabled="!!editingId"></label><label>通告标题 *<input v-model="form.title"></label></div></div>
        <div class="field-group wide"><h3>Q 行</h3><div class="group-grid q-grid"><label>FIR *<select v-model="form.fir"><option value="EAAD">EAAD</option></select></label><label>Q-CODE *<input v-model="form.qCode" maxlength="5" placeholder="例如 QFALC" :readonly="form.scenario==='AD.CLS'||form.scenario==='AD.LIM'" :title="form.scenario.startsWith('AD.')?'发布时依据 XML 自动生成':''"></label><label>TRAFFIC *<select v-model="form.traffic" :disabled="form.scenario==='AD.LIM'"><option>I</option><option>V</option><option>IV</option></select></label><label>PURPOSE *<select v-model="form.purpose" :disabled="form.scenario==='AD.LIM'"><option>N</option><option>B</option><option>O</option><option>NB</option><option>NO</option><option>BO</option><option>NBO</option></select></label><label>SCOPE *<select v-model="form.scope" :disabled="form.scenario==='AD.LIM'"><option>A</option><option>E</option><option>AE</option></select></label><label>纬度（十进制度）<div class="inline-input"><input v-model="form.latitude" type="number" min="0" max="90" step="any"><select v-model="form.latitudeHemisphere"><option>N</option><option>S</option></select></div></label><label>经度（十进制度）<div class="inline-input"><input v-model="form.longitude" type="number" min="0" max="180" step="any"><select v-model="form.longitudeHemisphere"><option>E</option><option>W</option></select></div></label><label>影响半径（NM）<input v-model="form.radiusNm" type="number" min="0" max="999"></label></div>
          <div class="limit-grid"><label>下限类型<select v-model="form.lowerRestricted"><option :value="false">无限制（000）</option><option :value="true">指定米数</option></select></label><label>下限高度（米）<input v-model="form.lowerMeters" type="number" min="0" max="16000" :disabled="!form.lowerRestricted"><small>换算结果：FL{{fl(form.lowerRestricted?form.lowerMeters:'',false)}}</small></label><label>上限类型<select v-model="form.upperRestricted"><option :value="false">无限制（999）</option><option :value="true">指定米数</option></select></label><label>上限高度（米）<input v-model="form.upperMeters" type="number" min="0" max="16000" :disabled="!form.upperRestricted"><small>换算结果：FL{{fl(form.upperRestricted?form.upperMeters:'',true)}}</small></label></div>
        </div>
        <div class="field-group wide abc-fields"><label>A 项：机场<select v-model="form.airport" @change="airportChanged"><option v-for="a in airports" :key="a.designator" :value="a.designator">{{a.designator}} — {{a.name}} ({{a.type}})</option></select><small v-if="airports.find(a=>a.designator===form.airport)">FIR {{form.fir}} · {{airports.find(a=>a.designator===form.airport).firSource}}</small></label><label>B 项：开始时间 *<input v-model="form.effectiveStart" type="datetime-local"></label><label>C 项：结束时间 *<input v-model="form.effectiveEnd" type="datetime-local"></label></div>
        <div v-if="form.scenario==='AD.CLS'" class="field-group wide"><h3>Q 行人工修正（可选）</h3><div class="group-grid"><label>修改原因<input v-model="form.qOverrideReason" placeholder="留空则采用系统自动值"></label><label>操作员<input v-model="form.qOverrideOperator" :disabled="!form.qOverrideReason"></label><label>修正 Q-code<input v-model="form.qCode" maxlength="5" :disabled="!form.qOverrideReason"></label><label>修正 Traffic<select v-model="form.traffic" :disabled="!form.qOverrideReason"><option>I</option><option>V</option><option>IV</option></select></label><label>修正 Purpose<select v-model="form.purpose" :disabled="!form.qOverrideReason"><option>N</option><option>B</option><option>O</option><option>NB</option><option>NO</option><option>BO</option><option>NBO</option></select></label><label>修正 Scope<select v-model="form.scope" :disabled="!form.qOverrideReason"><option>A</option><option>E</option><option>AE</option></select></label></div><small>人工修正只影响 NOTAM Q 行，不改变 Event/TEMPDELTA。</small></div>
        <div v-if="form.scenario==='RWY.CLS'" class="field-group wide"><h3>RWY.CLS 场景数据</h3><div class="runway-options"><label v-for="r in runways" :key="r.designator" :class="{unsupported:!r.supported}"><input type="checkbox" :checked="form.selectedRunways===r.designator" :disabled="!r.supported" @change="form.selectedRunways=$event.target.checked?r.designator:''"><span><b>{{r.designator}}</b><small>{{r.supported?'关闭该跑道的全部方向':'当前RWY.CLS模板未支持'}}</small></span></label></div></div>
        <div v-if="form.scenario==='TWY.CLS'" class="field-group wide"><h3>TWY.CLS 场景数据</h3><div class="runway-options"><label v-for="t in taxiways" :key="t.designator"><input type="checkbox" :checked="form.selectedTaxiways.split(',').includes(t.designator)" @change="toggleTaxiway(t.designator,$event.target.checked)"><span><b>TWY {{t.designator}}</b><small>关闭整条滑行道</small></span></label></div><small>滑行道编号来自所选机场的 AIXM Baseline 数据。</small></div>
        <div v-if="form.scenario==='AD.LIM'" class="field-group wide adlim-limits"><div class="adlim-title"><h3>AD.LIM 使用限制</h3></div><div class="adlim-common"><label>限制类型 *<select v-model="form.limitationType"><option value="CONDITIONAL">Conditional for</option><option value="RESERV">Closed, except for</option><option value="FORBID">Prohibited for</option><option value="PERMIT">Additionally allowed for</option></select></label></div>
          <article v-for="(r,index) in restrictions" :key="index" class="restriction-card"><header><b>限制条件 {{index+1}}</b><div><button type="button" class="link" :disabled="index===0" @click="moveRestriction(index,-1)">上移</button><button type="button" class="link" :disabled="index===restrictions.length-1" @click="moveRestriction(index,1)">下移</button><button type="button" class="link delete" :disabled="restrictions.length===1" @click="removeRestriction(index)">删除</button></div></header>
            <div class="adlim-head"><label>Operation *<select v-model="r.operation"><option>ALL</option><option>LANDING</option><option>TAKEOFF</option><option>TOUCHGO</option><option>TRAIN_APPROACH</option><option>ALTN_LANDING</option><option>AIRSHOW</option><option value="OTHER">OTHER</option></select></label><label v-if="r.operation==='OTHER'">Operation other *<input v-model="r.operationOther"></label></div>
            <section class="limit-section"><label class="limit-toggle"><input v-model="r.includeAircraft" type="checkbox"><b>Aircraft</b><span>添加航空器限制</span></label><div v-if="r.includeAircraft" class="limit-subgrid"><label>Type<select v-model="r.aircraftType"><option value="">不限制</option><option v-for="x in ['LANDPLANE','SEAPLANE','AMPHIBIAN','HELICOPTER','GYROCOPTER','TILT_WING','STOL','GLIDER','HANGGLIDER','PARAGLIDER','ULTRA_LIGHT','BALLOON','UAV','ALL']" :key="x">{{x}}</option><option value="OTHER">OTHER</option></select></label><label v-if="r.aircraftType==='OTHER'">Type other *<input v-model="r.aircraftTypeOther"></label><label>Engine<select v-model="r.aircraftEngine"><option value="">不限制</option><option v-for="x in ['JET','PISTON','TURBOPROP','ALL']" :key="x">{{x}}</option><option value="OTHER">OTHER</option></select></label><label v-if="r.aircraftEngine==='OTHER'">Engine other *<input v-model="r.aircraftEngineOther"></label><label>Wing span<input v-model="r.aircraftWingSpan" type="number" min="0"></label><label>Wing span unit<select v-model="r.aircraftWingSpanUom"><option>M</option><option>FT</option></select></label><label>Wing span interpretation<select v-model="r.aircraftWingSpanInterpretation"><option value="">不限制</option><option v-for="x in ['ABOVE','AT_OR_ABOVE','AT_OR_BELOW','BELOW']" :key="x">{{x}}</option></select></label><label>Weight<input v-model="r.aircraftWeight" type="number" min="0"></label><label>Weight unit<select v-model="r.aircraftWeightUom"><option>KG</option><option>T</option><option>LB</option></select></label><label>Weight interpretation<select v-model="r.aircraftWeightInterpretation"><option value="">不限制</option><option v-for="x in ['ABOVE','AT_OR_ABOVE','AT_OR_BELOW','BELOW']" :key="x">{{x}}</option></select></label></div></section>
            <section class="limit-section"><label class="limit-toggle"><input v-model="r.includeFlight" type="checkbox"><b>Flight</b><span>添加飞行限制</span></label><div v-if="r.includeFlight" class="limit-subgrid"><template v-for="field in [{key:'flightType',label:'Type',values:['OAT','GAT','ALL']},{key:'flightRule',label:'Rule',values:['IFR','VFR','ALL']},{key:'flightStatus',label:'Status',values:['HEAD','STATE','HUM','HOSP','SAR','ALL','EMERGENCY']},{key:'flightMilitary',label:'Military',values:['MIL','CIVIL','ALL']},{key:'flightOrigin',label:'Origin',values:['NTL','INTL','ALL','HOME_BASED']},{key:'flightPurpose',label:'Purpose',values:['SCHEDULED','NON_SCHEDULED','PRIVATE','AIR_TRAINING','AIR_WORK','ALL','PARTICIPANT']}]" :key="field.key"><label>{{field.label}}<select v-model="r[field.key]"><option value="">不限制</option><option v-for="x in field.values" :key="x">{{x}}</option><option value="OTHER">OTHER</option></select></label><label v-if="r[field.key]==='OTHER'">{{field.label}} other *<input v-model="r[`${field.key}Other`]"></label></template></div></section>
            <section class="limit-section"><label class="limit-toggle"><input v-model="r.includePpr" type="checkbox"><b>PPR</b><span>添加事先许可要求</span></label><div v-if="r.includePpr" class="limit-subgrid"><label>PPR 时间 *<input v-model="r.pprValue" type="number" min="0"></label><label>时间单位 *<select v-model="r.pprUnit"><option>HR</option><option>MIN</option><option>SEC</option></select></label><label>PPR details<input v-model="r.pprDetails"></label></div></section>
          </article><div class="add-restriction"><button type="button" class="primary" @click="addRestriction">＋ 添加限制条件</button></div><small>XML 与 E 项按卡片顺序生成；Q-code 仅由第一个限制条件确定。</small>
        </div>
        <div class="field-group wide"><h3>D 项：时间计划（UTC）</h3><div class="group-grid schedule"><label>生效方式<select v-model="form.scheduleMode" @change="scheduleModeChanged"><option value="CONTINUOUS">整个B–C有效期连续生效</option><option value="DAILY">Daily</option><option value="WEEKDAYS">Weekdays</option><option value="DATES">Dates</option></select></label><template v-if="form.scheduleMode!=='CONTINUOUS'"><div v-if="form.scheduleMode==='WEEKDAYS'" class="weekday-picker"><span>适用星期 *</span><label v-for="day in weekdays" :key="day[0]"><input v-model="form.scheduleDays" type="checkbox" :value="day[0]">{{day[1]}}</label></div><template v-if="form.scheduleMode==='DATES'"><label>开始日期 *<input v-model="form.scheduleStartDate" type="date"></label><label>结束日期 *<input v-model="form.scheduleEndDate" type="date"></label></template><label>开始时间 *<input v-model="form.scheduleStart" type="time"></label><label>结束时间 *<input v-model="form.scheduleEnd" type="time"></label></template></div><small v-if="form.scheduleMode==='CONTINUOUS'">连续模式不会生成 Timesheet。</small><small v-else>第一版仅支持明确的 startTime/endTime，不支持 SR/SS 或相对时间。</small></div>
        <div class="field-group wide"><h3>E 项：结构化事件数据</h3><div class="group-grid structured-e"><label v-if="form.scenario!=='AD.LIM'">事件 *<select v-model="form.eventDescription"><option v-for="option in eventOptions" :key="option[0]" :value="option[0]">{{option[1]}}</option></select></label><label>原因{{form.scenario==='AD.CLS'||form.scenario==='AD.LIM'?'（可选）':' *'}}<input v-model="form.reason" placeholder="例如 SURFACE MAINTENANCE"></label><label>备注<input v-model="form.remarks" placeholder="可选，例如 RUBBER REMOVAL"></label></div></div>
        <label>F 项：下限（仅QW/QR）<input :value="itemF()" readonly></label><label>G 项：上限（仅QW/QR）<input :value="itemG()" readonly></label>
      </div>
      <div class="actions"><button @click="view='list';editingId=null">取消</button><button class="primary" @click="create">{{editingId?'保存修改':'保存为草稿'}}</button></div>
    </section>
    <section v-else class="detail">
      <div class="panel summary"><div><span class="pill" :class="selected.status.toLowerCase()">{{selected.status==='DRAFT'?'草稿':'已发布'}}</span><h2>{{selected.title}}</h2><p>{{selected.number}} · {{selected.airport}}</p></div><div class="summary-actions"><button class="danger" @click="remove(selected)">删除通告</button><button v-if="selected.status==='DRAFT'" @click="editDraft(selected)">继续编辑</button><button v-if="selected.status==='DRAFT'" class="primary" @click="publish(selected)">发布通告</button></div></div>
      <section class="panel notam-card"><h3>NOTAM</h3><div class="notam-fields"><div class="field-row q"><b>Q)</b><span>{{qLine(selected)}}</span></div><div class="field-row"><b>A)</b><span>{{selected.airport}}</span></div><div class="field-row"><b>B)</b><span>{{compact(selected.effectiveStart)}} UTC</span></div><div class="field-row"><b>C)</b><span>{{compact(selected.effectiveEnd)}} UTC</span></div><div class="field-row"><b>D)</b><span>{{scheduleText(selected)}}</span></div><div class="field-row"><b>E)</b><span>{{selected.condition}}</span></div><div class="field-row"><b>F)</b><span>{{itemF(selected)}}</span></div><div class="field-row"><b>G)</b><span>{{itemG(selected)}}</span></div></div></section>
      <div class="cols"><section class="panel info"><h3>通告信息</h3><dl><div><dt>场景 / 航空要素</dt><dd>{{selected.scenario}} / {{selected.featureType}}</dd></div><div><dt>有效期</dt><dd>{{dt(selected.effectiveStart)}} 至<br>{{dt(selected.effectiveEnd)}}</dd></div><div><dt>坐标</dt><dd>{{selected.latitude}}, {{selected.longitude}} / {{selected.radiusNm}} NM</dd></div></dl><h3>CNOTAM转换结果</h3><pre class="cnotam">{{cnotam}}</pre></section><section class="panel xml"><h3>AIXM 5.1.1 XML预览</h3><pre>{{xml}}</pre></section></div>
    </section>
  </main>
</div>
</template>
