package com.example.digitalnotam.scenario.adlim;

import com.example.digitalnotam.domain.Notam;
import com.example.digitalnotam.domain.AdLimRestriction;
import com.example.digitalnotam.workflow.DigitalNotamPipeline;
import org.w3c.dom.Document;
import java.time.Instant;
import java.util.List;
import java.nio.file.*;

public final class AdLimScenarioBuilderTest {
    public static void main(String[] args)throws Exception{
        check("RESERV","LIMITED","ALL");check("FORBID","LIMITED","TRAIN_APPROACH");check("PERMIT","OTHER:EXTENDED","AIRSHOW");
        Notam conditional=notam("CONDITIONAL","LANDING","VFR","HELICOPTER","8","T","AT_OR_ABOVE","3","HR");Document d=new AdLimScenarioBuilder().build(conditional);text(d,"logicalOperator","AND");text(d,"priorPermission","3");new AdLimNotamProducer().produce(d,conditional);var xsd=DigitalNotamPipeline.class.getDeclaredMethod("validateXsd",Document.class);xsd.setAccessible(true);xsd.invoke(null,d);
        AdLimRestriction first=new AdLimRestriction("RESERV","ALL","","","","","HOME_BASED","","","","","","","","","","","","");AdLimRestriction second=new AdLimRestriction("RESERV","TRAIN_APPROACH","","VFR","","","","","","","","","","","","","","","");Notam multiple=notam("RESERV","ALL","","","","","","","").withAdLimRestrictions(List.of(first,second));Document multi=new AdLimScenarioBuilder().build(multiple);if(eventAvailabilityCount(multi)!=1)throw new AssertionError("Expected one event availability");if(eventUsageCount(multi)!=2)throw new AssertionError("Expected two event usages");if(reasonCount(multi)!=1)throw new AssertionError("Reason must be encoded once");new AdLimNotamProducer().produce(multi,multiple);text(multi,"selectionCode","QFALB");String itemE=notamText(multi);if(!itemE.contains("AD CLOSED, EXCEPT FOR")||!itemE.contains("HOME BASED FLIGHTS")||!itemE.contains("VFR PRACTICE OF LOW APPROACHES"))throw new AssertionError("Unexpected E item: "+itemE);if(itemE.contains("HOME_BASED")||itemE.contains("TRAIN_APPROACH"))throw new AssertionError("E item contains raw code: "+itemE);xsd.invoke(null,multi);var serialize=DigitalNotamPipeline.class.getDeclaredMethod("serialize",Document.class);serialize.setAccessible(true);String xml=(String)serialize.invoke(null,multi);assertFormatting(xml);String cnotam=new DigitalNotamPipeline().transform(xml,"AD.LIM");if(!cnotam.contains("QFALB"))throw new AssertionError("CNOTAM conversion failed");
        try{new AdLimScenarioBuilder().build(multiple.withAdLimRestrictions(List.of(first,new AdLimRestriction("FORBID","ALL","","","","","","","","","","","","","","","","",""))));throw new AssertionError("Mixed limitation types must be rejected");}catch(IllegalArgumentException expected){if(!expected.getMessage().contains("相同的限制类型"))throw expected;}
        Path legacy=Path.of("data","notams","A0010_26.xml");if(Files.exists(legacy))new DigitalNotamPipeline().transform(Files.readString(legacy),"AD.LIM");
        System.out.println("AD.LIM scenario tests passed");
    }
    private static void check(String type,String status,String operation)throws Exception{Notam n=notam(type,operation,"","","","","","","");Document d=new AdLimScenarioBuilder().build(n);text(d,"scenario","AD.LIM");text(d,"operationalStatus",status);text(d,"type",type);text(d,"operation",operation);var statuses=d.getElementsByTagNameNS("*","operationalStatus");int usages=-1;for(int i=0;i<statuses.getLength();i++)if(status.equals(statuses.item(i).getTextContent().trim()))usages=((org.w3c.dom.Element)statuses.item(i).getParentNode()).getElementsByTagNameNS("*","AirportHeliportUsage").getLength();if(usages!=1)throw new AssertionError("Expected one event usage");new AdLimNotamProducer().produce(d,n);var xsd=DigitalNotamPipeline.class.getDeclaredMethod("validateXsd",Document.class);xsd.setAccessible(true);xsd.invoke(null,d);}
    private static void text(Document d,String local,String expected){var nodes=d.getElementsByTagNameNS("*",local);boolean found=false;for(int i=0;i<nodes.getLength();i++)if(expected.equals(nodes.item(i).getTextContent().trim()))found=true;if(!found)throw new AssertionError(local+" != "+expected);}
    private static int eventAvailabilityCount(Document d){int count=0;var statuses=d.getElementsByTagNameNS("*","operationalStatus");for(int i=0;i<statuses.getLength();i++)if(java.util.Set.of("LIMITED","OTHER:EXTENDED").contains(statuses.item(i).getTextContent().trim()))count++;return count;}
    private static int eventUsageCount(Document d){var statuses=d.getElementsByTagNameNS("*","operationalStatus");for(int i=0;i<statuses.getLength();i++)if(java.util.Set.of("LIMITED","OTHER:EXTENDED").contains(statuses.item(i).getTextContent().trim()))return((org.w3c.dom.Element)statuses.item(i).getParentNode()).getElementsByTagNameNS("*","AirportHeliportUsage").getLength();return 0;}
    private static int reasonCount(Document d){int count=0;var nodes=d.getElementsByTagNameNS("*","propertyName");for(int i=0;i<nodes.getLength();i++)if("operationalStatus".equals(nodes.item(i).getTextContent().trim()))count++;return count;}
    private static String notamText(Document d){var nodes=d.getElementsByTagNameNS("*","text");for(int i=0;i<nodes.getLength();i++)if(nodes.item(i).getParentNode()!=null&&"NOTAM".equals(nodes.item(i).getParentNode().getLocalName()))return nodes.item(i).getTextContent();throw new AssertionError("NOTAM text not found");}
    private static void assertFormatting(String xml){String nl=System.lineSeparator();if(!xml.contains("<message:AIXMBasicMessage"+nl+"  xmlns:"))throw new AssertionError("Root attributes must start on a new line");if(xml.matches("(?s).*-->[ \\t]*<message:AIXMBasicMessage.*"))throw new AssertionError("Header comment and root element must be on separate lines");if(!xml.contains(nl+"  <message:hasMember"))throw new AssertionError("XML must use two-space indentation");}
    private static Notam notam(String limit,String operation,String rule,String aircraft,String weight,String weightUom,String weightInterpretation,String ppr,String pprUnit){String now=Instant.now().toString();return new Notam("adlim-test","A8888/26","AD.LIM","AD LIMITATION","EADD","AIRPORT_HELIPORT","","","","LIMITED","MAINTENANCE","NOTE","2026-08-01T08:00:00Z","2026-08-02T18:00:00Z","52.37166667","31.94944444","5","N","W","QFALT","IV","NBO","A","","","CONTINUOUS","ANY","08:00","18:00","DRAFT",now,now,"EAAD","","","","","",limit,operation,"",rule,"","","","",aircraft,"","","M","",weight,weightUom,weightInterpretation,ppr,pprUnit,ppr.isBlank()?"":"CONTACT OPS",List.of(),"","","");}
}
