package com.example.digitalnotam.scenario.adlim;

import com.example.digitalnotam.baseline.BaselineAirportHeliportCatalog;
import com.example.digitalnotam.domain.Notam;
import com.example.digitalnotam.scenario.common.QCodeDefaults;
import com.example.digitalnotam.xml.CommonDigitalNotamBuilder;
import org.w3c.dom.*;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

public final class AdLimNotamProducer {
    private static final Map<String,String> FLIGHT_TYPE=Map.of("OAT","OPERATIONAL AIR TRAFFIC","GAT","GENERAL AIR TRAFFIC","ALL","OPERATIONAL AIR TRAFFIC/GENERAL AIR TRAFFIC");
    private static final Map<String,String> FLIGHT_RULE=Map.of("IFR","IFR","VFR","VFR","ALL","IFR/VFR");
    private static final Map<String,String> FLIGHT_STATUS=Map.of("HEAD","HEAD OF STATE","STATE","STATE ACFT","HUM","HUM","HOSP","HOSP","SAR","SAR","EMERGENCY","EMERG","ALL","STATE ACFT/HUM/HOSP/SAR/EMERG");
    private static final Map<String,String> MILITARY=Map.of("MIL","MIL ACFT","CIVIL","CIVIL ACFT","ALL","CIVIL/MIL ACFT");
    private static final Map<String,String> ORIGIN=Map.of("NTL","DOMESTIC","INTL","INTL","HOME_BASED","HOME BASED","ALL","DOMESTIC/INTERNATIONAL");
    private static final Map<String,String> PURPOSE=Map.of("SCHEDULED","SCHEDULED","NON_SCHEDULED","NOT SCHEDULED","PRIVATE","PRIVATE","AIR_TRAINING","TRAINING","AIR_WORK","AERIAL WORK","PARTICIPANT","PARTICIPATING ACFT","ALL","SCHEDULED/NOT SCHEDULED/PRIVATE/TRAINING/AERIAL WORK/PARTICIPATING ACFT");
    private static final Map<String,String> AIRCRAFT_TYPE=Map.ofEntries(Map.entry("LANDPLANE","LANDPLANES"),Map.entry("SEAPLANE","SEAPLANES"),Map.entry("AMPHIBIAN","AMPHIBIANS"),Map.entry("HELICOPTER","HEL"),Map.entry("GYROCOPTER","GYROCOPTERS"),Map.entry("TILT_WING","TILT WING ACFT"),Map.entry("STOL","SHORT TAKE-OFF AND LANDING ACFT"),Map.entry("GLIDER","GLIDERS"),Map.entry("HANGGLIDER","HANG-GLIDERS"),Map.entry("PARAGLIDER","PARAGLIDERS"),Map.entry("ULTRA_LIGHT","ULTRA LIGHTS"),Map.entry("BALLOON","BALLOONS"),Map.entry("UAV","UNMANNED ACFT"),Map.entry("ALL","ALL ACFT TYPES"));
    private static final Map<String,String> ENGINE=Map.of("JET","JET ACFT","PISTON","PISTON ACFT","TURBOPROP","TURBOPROP ACFT","ALL","ALL ENGINE TYPES");
    private static final Map<String,String> WING=Map.of("ABOVE","ACFT WITH WINGSPAN MORE THAN","AT_OR_ABOVE","ACFT WITH WINGSPAN EQUAL TO OR MORE THAN","AT_OR_BELOW","ACFT WITH WINGSPAN EQUAL TO OR LESS THAN","BELOW","ACFT WITH WINGSPAN LESS THAN");
    private static final Map<String,String> WEIGHT=Map.of("ABOVE","ACFT MASS HEAVIER THAN","AT_OR_ABOVE","ACFT MASS EQUAL TO OR HEAVIER THAN","AT_OR_BELOW","ACFT MASS EQUAL TO OR LIGHTER THAN","BELOW","ACFT MASS LIGHTER THAN");
    private static final Map<String,String> OPERATION=Map.of("LANDING","LANDING","TAKEOFF","TAKE-OFF","TOUCHGO","TOUCH AND GO","TRAIN_APPROACH","PRACTICE OF LOW APPROACHES","ALTN_LANDING","ALTERNATE","AIRSHOW","ACFT PARTICIPATING IN AIR DISPLAY","ALL","FLIGHTS");
    private final BaselineAirportHeliportCatalog catalog=new BaselineAirportHeliportCatalog();private final QCodeDefaults defaults=new QCodeDefaults();private final AdLimQCodeResolver resolver=new AdLimQCodeResolver();

    public void produce(Document d,Notam n)throws Exception{var b=catalog.find(n.airport(),Instant.parse(n.effectiveStart()),Instant.parse(n.effectiveEnd()));Element availability=eventAvailability(d);String q=resolver.resolve(availability,"HP".equals(b.type()));String[] qp=defaults.get(q);String itemA=b.locationIndicatorIcao().isBlank()?b.designator().substring(0,2)+"XX":b.locationIndicatorIcao();for(String[] f:new String[][]{{"affectedFIR",b.firDesignator()},{"selectionCode",q},{"traffic",qp[0]},{"purpose",qp[1]},{"scope","A"},{"minimumFL","000"},{"maximumFL","999"},{"coordinates",coordinates(b.latitude(),b.longitude())},{"radius","005"},{"location",itemA},{"effectiveStart",time(n.effectiveStart())},{"effectiveEnd",endTime(n.effectiveEnd())},{"estimatedEnd","NO"},{"permanent","NO"},{"text",itemE(availability,b)}})CommonDigitalNotamBuilder.setNotam(d,f[0],f[1]);}

    private static String itemE(Element availability,BaselineAirportHeliportCatalog.AirportBaseline b){List<Element> usages=usages(availability);String commonType=BaselineAirportHeliportCatalog.text(usages.get(0),"type");if(usages.stream().anyMatch(u->!commonType.equals(BaselineAirportHeliportCatalog.text(u,"type"))))throw new IllegalArgumentException("E 项制作要求所有 Usage 使用相同 type");StringBuilder out=new StringBuilder(airportText(b)).append(' ').append(relation(commonType)).append(System.lineSeparator()).append(String.join(", ",usages.stream().map(AdLimNotamProducer::usageText).toList()));String reason="";List<String> notes=new ArrayList<>();for(Element wrapper:BaselineAirportHeliportCatalog.directChildren(availability,"annotation")){Element note=BaselineAirportHeliportCatalog.first(wrapper,"Note");if(note==null||!"REMARK".equals(BaselineAirportHeliportCatalog.text(note,"purpose")))continue;String value=BaselineAirportHeliportCatalog.text(note,"note");if("operationalStatus".equals(BaselineAirportHeliportCatalog.text(note,"propertyName")))reason=value;else if(!value.isBlank())notes.add(value);}if(!reason.isBlank())out.append(System.lineSeparator()).append("DUE TO ").append(reason.trim());for(String note:notes)out.append('.').append(System.lineSeparator()).append(note.trim());String result=out.toString().stripTrailing();if(!result.endsWith("."))result+=".";return result.toUpperCase(Locale.ENGLISH);}
    private static String airportText(BaselineAirportHeliportCatalog.AirportBaseline b){String type=switch(b.type()){case"HP"->"HELIPORT";case"LS","OTHER"->"LANDING SITE";default->"AD";};if(!b.locationIndicatorIcao().isBlank())return type;if(!b.name().isBlank())return type+" "+b.name();return type+" LOCATED AT "+coordinates(b.latitude(),b.longitude());}
    private static List<Element> usages(Element availability){List<Element> result=new ArrayList<>();for(Element wrapper:BaselineAirportHeliportCatalog.directChildren(availability,"usage")){Element usage=BaselineAirportHeliportCatalog.first(wrapper,"AirportHeliportUsage");if(usage!=null)result.add(usage);}if(result.isEmpty())throw new IllegalArgumentException("AD.LIM 缺少 AirportHeliportUsage");return result;}
    private static String usageText(Element usage){List<String> out=new ArrayList<>();Element flight=BaselineAirportHeliportCatalog.first(usage,"FlightCharacteristic"),aircraft=BaselineAirportHeliportCatalog.first(usage,"AircraftCharacteristic");if(flight!=null){decoded(out,FLIGHT_TYPE,BaselineAirportHeliportCatalog.text(flight,"type"));decoded(out,FLIGHT_RULE,BaselineAirportHeliportCatalog.text(flight,"rule"));decoded(out,FLIGHT_STATUS,BaselineAirportHeliportCatalog.text(flight,"status"));decoded(out,MILITARY,BaselineAirportHeliportCatalog.text(flight,"military"));decoded(out,ORIGIN,BaselineAirportHeliportCatalog.text(flight,"origin"));decoded(out,PURPOSE,BaselineAirportHeliportCatalog.text(flight,"purpose"));}if(aircraft!=null){decoded(out,AIRCRAFT_TYPE,BaselineAirportHeliportCatalog.text(aircraft,"type"));decoded(out,ENGINE,BaselineAirportHeliportCatalog.text(aircraft,"engine"));measure(out,aircraft,"wingSpan","wingSpanInterpretation",WING);measure(out,aircraft,"weight","weightInterpretation",WEIGHT);}decoded(out,OPERATION,BaselineAirportHeliportCatalog.text(usage,"operation"));Element ppr=BaselineAirportHeliportCatalog.first(usage,"priorPermission");if(ppr!=null&&!ppr.getTextContent().trim().isBlank()){String value="PPR "+ppr.getTextContent().trim()+" "+switch(ppr.getAttribute("uom")){case"HR"->"HR";case"MIN"->"MIN";case"SEC"->"SEC";default->other(ppr.getAttribute("uom"));};for(Element wrapper:BaselineAirportHeliportCatalog.directChildren(usage,"annotation")){Element note=BaselineAirportHeliportCatalog.first(wrapper,"Note");if(note!=null&&"priorPermission".equals(BaselineAirportHeliportCatalog.text(note,"propertyName"))&&"REMARK".equals(BaselineAirportHeliportCatalog.text(note,"purpose")))value+=" "+BaselineAirportHeliportCatalog.text(note,"note");}out.add(value);}return String.join(" ",out);}
    private static void measure(List<String> out,Element parent,String valueName,String interpretationName,Map<String,String> map){Element value=BaselineAirportHeliportCatalog.first(parent,valueName);if(value==null||value.getTextContent().trim().isBlank())return;String interpretation=BaselineAirportHeliportCatalog.text(parent,interpretationName),prefix=interpretation.isBlank()?"":decode(map,interpretation)+" ";out.add(prefix+value.getTextContent().trim()+" "+value.getAttribute("uom"));}
    private static void decoded(List<String> out,Map<String,String> map,String value){if(value!=null&&!value.isBlank())out.add(decode(map,value));}private static String decode(Map<String,String> map,String value){if(value.startsWith("OTHER:"))return other(value);String result=map.get(value);if(result==null)throw new IllegalArgumentException("AD.LIM E 项缺少解码映射: "+value);return result;}private static String other(String value){return value.replaceFirst("^OTHER:","").replace('_',' ').toLowerCase(Locale.ENGLISH);}
    private static String relation(String type){return switch(type){case"CONDITIONAL"->"AVAILABLE FOR";case"RESERV"->"CLOSED, EXCEPT FOR";case"FORBID"->"PROHIBITED FOR";case"PERMIT"->"NOW AVAILABLE FOR";default->throw new IllegalArgumentException("未知 usage type: "+type);};}
    private static Element eventAvailability(Document d){Element found=null;for(Element status:CommonDigitalNotamBuilder.all(d,CommonDigitalNotamBuilder.AIXM,"operationalStatus"))if(Set.of("LIMITED","OTHER:EXTENDED").contains(status.getTextContent().trim())){if(found!=null)throw new IllegalArgumentException("AD.LIM E 项制作要求恰好一个事件 availability");found=(Element)status.getParentNode();}if(found==null)throw new IllegalArgumentException("AD.LIM 缺少事件 availability");return found;}
    private static String time(String iso){return Instant.parse(iso).atZone(ZoneOffset.UTC).format(DateTimeFormatter.ofPattern("yyMMddHHmm"));}private static String endTime(String iso){ZonedDateTime z=Instant.parse(iso).atZone(ZoneOffset.UTC);return z.toLocalTime().equals(LocalTime.MIDNIGHT)?z.minusDays(1).format(DateTimeFormatter.ofPattern("yyMMdd"))+"2359":z.format(DateTimeFormatter.ofPattern("yyMMddHHmm"));}private static String coordinates(String lat,String lon){return coordinate(lat,2,Double.parseDouble(lat)<0?"S":"N")+coordinate(lon,3,Double.parseDouble(lon)<0?"W":"E");}private static String coordinate(String v,int width,String h){double x=Math.abs(Double.parseDouble(v));int d=(int)x,m=(int)Math.round((x-d)*60);if(m==60){d++;m=0;}return("%0"+width+"d%02d%s").formatted(d,m,h);}
}
