package com.example.digitalnotam.scenario.rwycls;

import com.example.digitalnotam.baseline.BaselineRunwayCatalog;import com.example.digitalnotam.domain.Notam;import com.example.digitalnotam.workflow.DigitalNotamPipeline;import org.w3c.dom.Document;import java.time.Instant;

public final class RwyClsScenarioBuilderTest {
    public static void main(String[] args)throws Exception{var catalog=new BaselineRunwayCatalog();var values=catalog.list("EADD",Instant.parse("2026-08-01T08:00:00Z"),Instant.parse("2026-08-02T18:00:00Z"));if(values.size()!=3||values.stream().anyMatch(x->x.directions().size()!=2))throw new AssertionError("EADD runway baseline relations not resolved");var runway=values.stream().filter(x->"09L/27R".equals(x.designator())).findFirst().orElseThrow();Notam full=notam("09L/27R").withRwyClsTarget("RUNWAY",runway.uuid(),"");Document d=new RwyClsScenarioBuilder().build(full);if(d.getElementsByTagNameNS("*","RunwayDirection").getLength()!=2)throw new AssertionError("Full runway must create two directions");assertCommentBindings(d);new RwyClsNotamProducer().produce(d,full);text(d,"selectionCode","QMRLC");contains(d,"text","RWY 09L/27R CLSD DUE TO MAINT.");validate(d);var serialize=DigitalNotamPipeline.class.getDeclaredMethod("serialize",Document.class);serialize.setAccessible(true);String cnotam=new DigitalNotamPipeline().transform((String)serialize.invoke(null,d),"RWY.CLS");if(!cnotam.contains("QMRLC")||!cnotam.contains("RWY 09L/27R CLSD"))throw new AssertionError("RWY.CLS CNOTAM conversion failed: "+cnotam);var single=full.withRwyClsTarget("RUNWAY_DIRECTION",runway.uuid(),runway.directions().get(0).uuid());Document one=new RwyClsScenarioBuilder().build(single);new RwyClsNotamProducer().produce(one,single);if(one.getElementsByTagNameNS("*","RunwayDirection").getLength()!=1)throw new AssertionError("Single direction must create one TEMPDELTA");contains(one,"text","RWY "+runway.directions().get(0).designator()+" CLSD");validate(one);var fato=values.stream().filter(x->"FATO".equals(x.type())).findFirst().orElseThrow();Notam f=notam(fato.designator()).withRwyClsTarget("RUNWAY",fato.uuid(),"");Document fd=new RwyClsScenarioBuilder().build(f);new RwyClsNotamProducer().produce(fd,f);text(fd,"selectionCode","QFHLC");contains(fd,"text","FATO 13/31 CLSD");validate(fd);System.out.println("RWY.CLS scenario tests passed");}
    private static Notam notam(String designator){return new Notam("rwy-test","D9999/26","RWY.CLS","RUNWAY CLOSURE","EADD","RUNWAY","RWY "+designator+" CLSD",designator,"","CLSD","MAINT","NOTE","2026-08-01T08:00:00Z","2026-08-02T18:00:00Z","52.37166667","31.94944444","5","N","W","QMRLC","IV","NBO","A","","","CONTINUOUS","ANY","08:00","18:00","DRAFT","2026-07-23T00:00:00Z","2026-07-23T00:00:00Z");}
    private static void validate(Document d)throws Exception{var m=DigitalNotamPipeline.class.getDeclaredMethod("validateXsd",Document.class);m.setAccessible(true);m.invoke(null,d);}
    private static void text(Document d,String local,String expected){var nodes=d.getElementsByTagNameNS("*",local);for(int i=0;i<nodes.getLength();i++)if(expected.equals(nodes.item(i).getTextContent().trim()))return;throw new AssertionError(local+" != "+expected);}
    private static void contains(Document d,String local,String expected){var nodes=d.getElementsByTagNameNS("*",local);for(int i=0;i<nodes.getLength();i++)if(nodes.item(i).getTextContent().contains(expected))return;throw new AssertionError(local+" missing "+expected);}
    private static void assertCommentBindings(Document d){var members=d.getElementsByTagNameNS("*","hasMember");int directions=0;for(int i=0;i<members.getLength();i++){var member=members.item(i);if(((org.w3c.dom.Element)member).getElementsByTagNameNS("*","RunwayDirection").getLength()==0)continue;directions++;var comment=previousSignificant(member);if(comment==null||comment.getNodeType()!=org.w3c.dom.Node.COMMENT_NODE||!comment.getNodeValue().trim().matches("(?:RWY|FATO)\\s+.+"))throw new AssertionError("RunwayDirection feature label comment is not bound to its member");}if(directions!=2)throw new AssertionError("Expected two direction comment bindings");var statuses=d.getElementsByTagNameNS("*","operationalStatus");for(int s=0;s<statuses.getLength();s++){if(!"CLOSED".equals(statuses.item(s).getTextContent().trim()))continue;var availability=(org.w3c.dom.Element)statuses.item(s).getParentNode();var annotations=availability.getElementsByTagNameNS("*","annotation");for(int i=0;i<annotations.getLength();i++){var annotation=(org.w3c.dom.Element)annotations.item(i);var note=(org.w3c.dom.Element)annotation.getElementsByTagNameNS("*","Note").item(0);String expected=note.getElementsByTagNameNS("*","propertyName").getLength()>0?"Closure Reason":"Note";var comment=previousSignificant(annotation);if(comment==null||comment.getNodeType()!=org.w3c.dom.Node.COMMENT_NODE||!expected.equals(comment.getNodeValue().trim()))throw new AssertionError(expected+" comment is not bound to its annotation");}}}
    private static org.w3c.dom.Node previousSignificant(org.w3c.dom.Node node){for(var n=node.getPreviousSibling();n!=null;n=n.getPreviousSibling())if(n.getNodeType()!=org.w3c.dom.Node.TEXT_NODE||!n.getTextContent().isBlank())return n;return null;}
}
